// <auto-generated />
using System;
using BankDataDb.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankDataDb.Migrations
{
    [DbContext(typeof(BankDataContext))]
    [Migration("20250713160338_card_add_comment")]
    partial class card_add_comment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("BankDataDb.Entities.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("BankDataDb.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BankId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardType")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("BankDataDb.Entities.CardTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountInMinorUnit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryAlpha3Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("TransactionTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryAlpha3Code");

                    b.HasIndex("CurrencyCode");

                    b.ToTable("CardTransactions");
                });

            modelBuilder.Entity("BankDataDb.Entities.Country", b =>
                {
                    b.Property<string>("Alpha3Code")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "alpha3");

                    b.Property<string>("Alpha2Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "alpha2");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<short>("NumericCode")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.HasKey("Alpha3Code");

                    b.HasIndex("Alpha2Code")
                        .IsUnique();

                    b.HasIndex("Alpha3Code")
                        .IsUnique();

                    b.HasIndex("NumericCode")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Alpha3Code = "AFG",
                            Alpha2Code = "AF",
                            EnglishName = "Afghanistan",
                            NumericCode = (short)4
                        },
                        new
                        {
                            Alpha3Code = "ALB",
                            Alpha2Code = "AL",
                            EnglishName = "Albania",
                            NumericCode = (short)8
                        },
                        new
                        {
                            Alpha3Code = "DZA",
                            Alpha2Code = "DZ",
                            EnglishName = "Algeria",
                            NumericCode = (short)12
                        },
                        new
                        {
                            Alpha3Code = "AND",
                            Alpha2Code = "AD",
                            EnglishName = "Andorra",
                            NumericCode = (short)20
                        },
                        new
                        {
                            Alpha3Code = "AGO",
                            Alpha2Code = "AO",
                            EnglishName = "Angola",
                            NumericCode = (short)24
                        },
                        new
                        {
                            Alpha3Code = "ATG",
                            Alpha2Code = "AG",
                            EnglishName = "Antigua and Barbuda",
                            NumericCode = (short)28
                        },
                        new
                        {
                            Alpha3Code = "ARG",
                            Alpha2Code = "AR",
                            EnglishName = "Argentina",
                            NumericCode = (short)32
                        },
                        new
                        {
                            Alpha3Code = "ARM",
                            Alpha2Code = "AM",
                            EnglishName = "Armenia",
                            NumericCode = (short)51
                        },
                        new
                        {
                            Alpha3Code = "AUS",
                            Alpha2Code = "AU",
                            EnglishName = "Australia",
                            NumericCode = (short)36
                        },
                        new
                        {
                            Alpha3Code = "AUT",
                            Alpha2Code = "AT",
                            EnglishName = "Austria",
                            NumericCode = (short)40
                        },
                        new
                        {
                            Alpha3Code = "AZE",
                            Alpha2Code = "AZ",
                            EnglishName = "Azerbaijan",
                            NumericCode = (short)31
                        },
                        new
                        {
                            Alpha3Code = "BHS",
                            Alpha2Code = "BS",
                            EnglishName = "Bahamas",
                            NumericCode = (short)44
                        },
                        new
                        {
                            Alpha3Code = "BHR",
                            Alpha2Code = "BH",
                            EnglishName = "Bahrain",
                            NumericCode = (short)48
                        },
                        new
                        {
                            Alpha3Code = "BGD",
                            Alpha2Code = "BD",
                            EnglishName = "Bangladesh",
                            NumericCode = (short)50
                        },
                        new
                        {
                            Alpha3Code = "BRB",
                            Alpha2Code = "BB",
                            EnglishName = "Barbados",
                            NumericCode = (short)52
                        },
                        new
                        {
                            Alpha3Code = "BLR",
                            Alpha2Code = "BY",
                            EnglishName = "Belarus",
                            NumericCode = (short)112
                        },
                        new
                        {
                            Alpha3Code = "BEL",
                            Alpha2Code = "BE",
                            EnglishName = "Belgium",
                            NumericCode = (short)56
                        },
                        new
                        {
                            Alpha3Code = "BLZ",
                            Alpha2Code = "BZ",
                            EnglishName = "Belize",
                            NumericCode = (short)84
                        },
                        new
                        {
                            Alpha3Code = "BEN",
                            Alpha2Code = "BJ",
                            EnglishName = "Benin",
                            NumericCode = (short)204
                        },
                        new
                        {
                            Alpha3Code = "BTN",
                            Alpha2Code = "BT",
                            EnglishName = "Bhutan",
                            NumericCode = (short)64
                        },
                        new
                        {
                            Alpha3Code = "BOL",
                            Alpha2Code = "BO",
                            EnglishName = "Bolivia, Plurinational State of",
                            NumericCode = (short)68
                        },
                        new
                        {
                            Alpha3Code = "BIH",
                            Alpha2Code = "BA",
                            EnglishName = "Bosnia and Herzegovina",
                            NumericCode = (short)70
                        },
                        new
                        {
                            Alpha3Code = "BWA",
                            Alpha2Code = "BW",
                            EnglishName = "Botswana",
                            NumericCode = (short)72
                        },
                        new
                        {
                            Alpha3Code = "BRA",
                            Alpha2Code = "BR",
                            EnglishName = "Brazil",
                            NumericCode = (short)76
                        },
                        new
                        {
                            Alpha3Code = "BRN",
                            Alpha2Code = "BN",
                            EnglishName = "Brunei Darussalam",
                            NumericCode = (short)96
                        },
                        new
                        {
                            Alpha3Code = "BGR",
                            Alpha2Code = "BG",
                            EnglishName = "Bulgaria",
                            NumericCode = (short)100
                        },
                        new
                        {
                            Alpha3Code = "BFA",
                            Alpha2Code = "BF",
                            EnglishName = "Burkina Faso",
                            NumericCode = (short)854
                        },
                        new
                        {
                            Alpha3Code = "BDI",
                            Alpha2Code = "BI",
                            EnglishName = "Burundi",
                            NumericCode = (short)108
                        },
                        new
                        {
                            Alpha3Code = "CPV",
                            Alpha2Code = "CV",
                            EnglishName = "Cabo Verde",
                            NumericCode = (short)132
                        },
                        new
                        {
                            Alpha3Code = "KHM",
                            Alpha2Code = "KH",
                            EnglishName = "Cambodia",
                            NumericCode = (short)116
                        },
                        new
                        {
                            Alpha3Code = "CMR",
                            Alpha2Code = "CM",
                            EnglishName = "Cameroon",
                            NumericCode = (short)120
                        },
                        new
                        {
                            Alpha3Code = "CAN",
                            Alpha2Code = "CA",
                            EnglishName = "Canada",
                            NumericCode = (short)124
                        },
                        new
                        {
                            Alpha3Code = "CAF",
                            Alpha2Code = "CF",
                            EnglishName = "Central African Republic",
                            NumericCode = (short)140
                        },
                        new
                        {
                            Alpha3Code = "TCD",
                            Alpha2Code = "TD",
                            EnglishName = "Chad",
                            NumericCode = (short)148
                        },
                        new
                        {
                            Alpha3Code = "CHL",
                            Alpha2Code = "CL",
                            EnglishName = "Chile",
                            NumericCode = (short)152
                        },
                        new
                        {
                            Alpha3Code = "CHN",
                            Alpha2Code = "CN",
                            EnglishName = "China",
                            NumericCode = (short)156
                        },
                        new
                        {
                            Alpha3Code = "COL",
                            Alpha2Code = "CO",
                            EnglishName = "Colombia",
                            NumericCode = (short)170
                        },
                        new
                        {
                            Alpha3Code = "COM",
                            Alpha2Code = "KM",
                            EnglishName = "Comoros",
                            NumericCode = (short)174
                        },
                        new
                        {
                            Alpha3Code = "COG",
                            Alpha2Code = "CG",
                            EnglishName = "Congo",
                            NumericCode = (short)178
                        },
                        new
                        {
                            Alpha3Code = "COD",
                            Alpha2Code = "CD",
                            EnglishName = "Congo, Democratic Republic of the",
                            NumericCode = (short)180
                        },
                        new
                        {
                            Alpha3Code = "CRI",
                            Alpha2Code = "CR",
                            EnglishName = "Costa Rica",
                            NumericCode = (short)188
                        },
                        new
                        {
                            Alpha3Code = "CIV",
                            Alpha2Code = "CI",
                            EnglishName = "Côte d'Ivoire",
                            NumericCode = (short)384
                        },
                        new
                        {
                            Alpha3Code = "HRV",
                            Alpha2Code = "HR",
                            EnglishName = "Croatia",
                            NumericCode = (short)191
                        },
                        new
                        {
                            Alpha3Code = "CUB",
                            Alpha2Code = "CU",
                            EnglishName = "Cuba",
                            NumericCode = (short)192
                        },
                        new
                        {
                            Alpha3Code = "CYP",
                            Alpha2Code = "CY",
                            EnglishName = "Cyprus",
                            NumericCode = (short)196
                        },
                        new
                        {
                            Alpha3Code = "CZE",
                            Alpha2Code = "CZ",
                            EnglishName = "Czechia",
                            NumericCode = (short)203
                        },
                        new
                        {
                            Alpha3Code = "DNK",
                            Alpha2Code = "DK",
                            EnglishName = "Denmark",
                            NumericCode = (short)208
                        },
                        new
                        {
                            Alpha3Code = "DJI",
                            Alpha2Code = "DJ",
                            EnglishName = "Djibouti",
                            NumericCode = (short)262
                        },
                        new
                        {
                            Alpha3Code = "DMA",
                            Alpha2Code = "DM",
                            EnglishName = "Dominica",
                            NumericCode = (short)212
                        },
                        new
                        {
                            Alpha3Code = "DOM",
                            Alpha2Code = "DO",
                            EnglishName = "Dominican Republic",
                            NumericCode = (short)214
                        },
                        new
                        {
                            Alpha3Code = "ECU",
                            Alpha2Code = "EC",
                            EnglishName = "Ecuador",
                            NumericCode = (short)218
                        },
                        new
                        {
                            Alpha3Code = "EGY",
                            Alpha2Code = "EG",
                            EnglishName = "Egypt",
                            NumericCode = (short)818
                        },
                        new
                        {
                            Alpha3Code = "SLV",
                            Alpha2Code = "SV",
                            EnglishName = "El Salvador",
                            NumericCode = (short)222
                        },
                        new
                        {
                            Alpha3Code = "GNQ",
                            Alpha2Code = "GQ",
                            EnglishName = "Equatorial Guinea",
                            NumericCode = (short)226
                        },
                        new
                        {
                            Alpha3Code = "ERI",
                            Alpha2Code = "ER",
                            EnglishName = "Eritrea",
                            NumericCode = (short)232
                        },
                        new
                        {
                            Alpha3Code = "EST",
                            Alpha2Code = "EE",
                            EnglishName = "Estonia",
                            NumericCode = (short)233
                        },
                        new
                        {
                            Alpha3Code = "SWZ",
                            Alpha2Code = "SZ",
                            EnglishName = "Eswatini",
                            NumericCode = (short)748
                        },
                        new
                        {
                            Alpha3Code = "ETH",
                            Alpha2Code = "ET",
                            EnglishName = "Ethiopia",
                            NumericCode = (short)231
                        },
                        new
                        {
                            Alpha3Code = "FJI",
                            Alpha2Code = "FJ",
                            EnglishName = "Fiji",
                            NumericCode = (short)242
                        },
                        new
                        {
                            Alpha3Code = "FIN",
                            Alpha2Code = "FI",
                            EnglishName = "Finland",
                            NumericCode = (short)246
                        },
                        new
                        {
                            Alpha3Code = "FRA",
                            Alpha2Code = "FR",
                            EnglishName = "France",
                            NumericCode = (short)250
                        },
                        new
                        {
                            Alpha3Code = "GAB",
                            Alpha2Code = "GA",
                            EnglishName = "Gabon",
                            NumericCode = (short)266
                        },
                        new
                        {
                            Alpha3Code = "GMB",
                            Alpha2Code = "GM",
                            EnglishName = "Gambia",
                            NumericCode = (short)270
                        },
                        new
                        {
                            Alpha3Code = "GEO",
                            Alpha2Code = "GE",
                            EnglishName = "Georgia",
                            NumericCode = (short)268
                        },
                        new
                        {
                            Alpha3Code = "DEU",
                            Alpha2Code = "DE",
                            EnglishName = "Germany",
                            NumericCode = (short)276
                        },
                        new
                        {
                            Alpha3Code = "GHA",
                            Alpha2Code = "GH",
                            EnglishName = "Ghana",
                            NumericCode = (short)288
                        },
                        new
                        {
                            Alpha3Code = "GRC",
                            Alpha2Code = "GR",
                            EnglishName = "Greece",
                            NumericCode = (short)300
                        },
                        new
                        {
                            Alpha3Code = "GRD",
                            Alpha2Code = "GD",
                            EnglishName = "Grenada",
                            NumericCode = (short)308
                        },
                        new
                        {
                            Alpha3Code = "GTM",
                            Alpha2Code = "GT",
                            EnglishName = "Guatemala",
                            NumericCode = (short)320
                        },
                        new
                        {
                            Alpha3Code = "GIN",
                            Alpha2Code = "GN",
                            EnglishName = "Guinea",
                            NumericCode = (short)324
                        },
                        new
                        {
                            Alpha3Code = "GNB",
                            Alpha2Code = "GW",
                            EnglishName = "Guinea-Bissau",
                            NumericCode = (short)624
                        },
                        new
                        {
                            Alpha3Code = "GUY",
                            Alpha2Code = "GY",
                            EnglishName = "Guyana",
                            NumericCode = (short)328
                        },
                        new
                        {
                            Alpha3Code = "HTI",
                            Alpha2Code = "HT",
                            EnglishName = "Haiti",
                            NumericCode = (short)332
                        },
                        new
                        {
                            Alpha3Code = "HND",
                            Alpha2Code = "HN",
                            EnglishName = "Honduras",
                            NumericCode = (short)340
                        },
                        new
                        {
                            Alpha3Code = "HUN",
                            Alpha2Code = "HU",
                            EnglishName = "Hungary",
                            NumericCode = (short)348
                        },
                        new
                        {
                            Alpha3Code = "ISL",
                            Alpha2Code = "IS",
                            EnglishName = "Iceland",
                            NumericCode = (short)352
                        },
                        new
                        {
                            Alpha3Code = "IND",
                            Alpha2Code = "IN",
                            EnglishName = "India",
                            NumericCode = (short)356
                        },
                        new
                        {
                            Alpha3Code = "IDN",
                            Alpha2Code = "ID",
                            EnglishName = "Indonesia",
                            NumericCode = (short)360
                        },
                        new
                        {
                            Alpha3Code = "IRN",
                            Alpha2Code = "IR",
                            EnglishName = "Iran, Islamic Republic of",
                            NumericCode = (short)364
                        },
                        new
                        {
                            Alpha3Code = "IRQ",
                            Alpha2Code = "IQ",
                            EnglishName = "Iraq",
                            NumericCode = (short)368
                        },
                        new
                        {
                            Alpha3Code = "IRL",
                            Alpha2Code = "IE",
                            EnglishName = "Ireland",
                            NumericCode = (short)372
                        },
                        new
                        {
                            Alpha3Code = "ISR",
                            Alpha2Code = "IL",
                            EnglishName = "Israel",
                            NumericCode = (short)376
                        },
                        new
                        {
                            Alpha3Code = "ITA",
                            Alpha2Code = "IT",
                            EnglishName = "Italy",
                            NumericCode = (short)380
                        },
                        new
                        {
                            Alpha3Code = "JAM",
                            Alpha2Code = "JM",
                            EnglishName = "Jamaica",
                            NumericCode = (short)388
                        },
                        new
                        {
                            Alpha3Code = "JPN",
                            Alpha2Code = "JP",
                            EnglishName = "Japan",
                            NumericCode = (short)392
                        },
                        new
                        {
                            Alpha3Code = "JOR",
                            Alpha2Code = "JO",
                            EnglishName = "Jordan",
                            NumericCode = (short)400
                        },
                        new
                        {
                            Alpha3Code = "KAZ",
                            Alpha2Code = "KZ",
                            EnglishName = "Kazakhstan",
                            NumericCode = (short)398
                        },
                        new
                        {
                            Alpha3Code = "KEN",
                            Alpha2Code = "KE",
                            EnglishName = "Kenya",
                            NumericCode = (short)404
                        },
                        new
                        {
                            Alpha3Code = "KIR",
                            Alpha2Code = "KI",
                            EnglishName = "Kiribati",
                            NumericCode = (short)296
                        },
                        new
                        {
                            Alpha3Code = "PRK",
                            Alpha2Code = "KP",
                            EnglishName = "Korea, Democratic People's Republic of",
                            NumericCode = (short)408
                        },
                        new
                        {
                            Alpha3Code = "KOR",
                            Alpha2Code = "KR",
                            EnglishName = "Korea, Republic of",
                            NumericCode = (short)410
                        },
                        new
                        {
                            Alpha3Code = "KWT",
                            Alpha2Code = "KW",
                            EnglishName = "Kuwait",
                            NumericCode = (short)414
                        },
                        new
                        {
                            Alpha3Code = "KGZ",
                            Alpha2Code = "KG",
                            EnglishName = "Kyrgyzstan",
                            NumericCode = (short)417
                        },
                        new
                        {
                            Alpha3Code = "LAO",
                            Alpha2Code = "LA",
                            EnglishName = "Lao People's Democratic Republic",
                            NumericCode = (short)418
                        },
                        new
                        {
                            Alpha3Code = "LVA",
                            Alpha2Code = "LV",
                            EnglishName = "Latvia",
                            NumericCode = (short)428
                        },
                        new
                        {
                            Alpha3Code = "LBN",
                            Alpha2Code = "LB",
                            EnglishName = "Lebanon",
                            NumericCode = (short)422
                        },
                        new
                        {
                            Alpha3Code = "LSO",
                            Alpha2Code = "LS",
                            EnglishName = "Lesotho",
                            NumericCode = (short)426
                        },
                        new
                        {
                            Alpha3Code = "LBR",
                            Alpha2Code = "LR",
                            EnglishName = "Liberia",
                            NumericCode = (short)430
                        },
                        new
                        {
                            Alpha3Code = "LBY",
                            Alpha2Code = "LY",
                            EnglishName = "Libya",
                            NumericCode = (short)434
                        },
                        new
                        {
                            Alpha3Code = "LIE",
                            Alpha2Code = "LI",
                            EnglishName = "Liechtenstein",
                            NumericCode = (short)438
                        },
                        new
                        {
                            Alpha3Code = "LTU",
                            Alpha2Code = "LT",
                            EnglishName = "Lithuania",
                            NumericCode = (short)440
                        },
                        new
                        {
                            Alpha3Code = "LUX",
                            Alpha2Code = "LU",
                            EnglishName = "Luxembourg",
                            NumericCode = (short)442
                        },
                        new
                        {
                            Alpha3Code = "MDG",
                            Alpha2Code = "MG",
                            EnglishName = "Madagascar",
                            NumericCode = (short)450
                        },
                        new
                        {
                            Alpha3Code = "MWI",
                            Alpha2Code = "MW",
                            EnglishName = "Malawi",
                            NumericCode = (short)454
                        },
                        new
                        {
                            Alpha3Code = "MYS",
                            Alpha2Code = "MY",
                            EnglishName = "Malaysia",
                            NumericCode = (short)458
                        },
                        new
                        {
                            Alpha3Code = "MDV",
                            Alpha2Code = "MV",
                            EnglishName = "Maldives",
                            NumericCode = (short)462
                        },
                        new
                        {
                            Alpha3Code = "MLI",
                            Alpha2Code = "ML",
                            EnglishName = "Mali",
                            NumericCode = (short)466
                        },
                        new
                        {
                            Alpha3Code = "MLT",
                            Alpha2Code = "MT",
                            EnglishName = "Malta",
                            NumericCode = (short)470
                        },
                        new
                        {
                            Alpha3Code = "MHL",
                            Alpha2Code = "MH",
                            EnglishName = "Marshall Islands",
                            NumericCode = (short)584
                        },
                        new
                        {
                            Alpha3Code = "MRT",
                            Alpha2Code = "MR",
                            EnglishName = "Mauritania",
                            NumericCode = (short)478
                        },
                        new
                        {
                            Alpha3Code = "MUS",
                            Alpha2Code = "MU",
                            EnglishName = "Mauritius",
                            NumericCode = (short)480
                        },
                        new
                        {
                            Alpha3Code = "MEX",
                            Alpha2Code = "MX",
                            EnglishName = "Mexico",
                            NumericCode = (short)484
                        },
                        new
                        {
                            Alpha3Code = "FSM",
                            Alpha2Code = "FM",
                            EnglishName = "Micronesia, Federated States of",
                            NumericCode = (short)583
                        },
                        new
                        {
                            Alpha3Code = "MDA",
                            Alpha2Code = "MD",
                            EnglishName = "Moldova, Republic of",
                            NumericCode = (short)498
                        },
                        new
                        {
                            Alpha3Code = "MCO",
                            Alpha2Code = "MC",
                            EnglishName = "Monaco",
                            NumericCode = (short)492
                        },
                        new
                        {
                            Alpha3Code = "MNG",
                            Alpha2Code = "MN",
                            EnglishName = "Mongolia",
                            NumericCode = (short)496
                        },
                        new
                        {
                            Alpha3Code = "MNE",
                            Alpha2Code = "ME",
                            EnglishName = "Montenegro",
                            NumericCode = (short)499
                        },
                        new
                        {
                            Alpha3Code = "MAR",
                            Alpha2Code = "MA",
                            EnglishName = "Morocco",
                            NumericCode = (short)504
                        },
                        new
                        {
                            Alpha3Code = "MOZ",
                            Alpha2Code = "MZ",
                            EnglishName = "Mozambique",
                            NumericCode = (short)508
                        },
                        new
                        {
                            Alpha3Code = "MMR",
                            Alpha2Code = "MM",
                            EnglishName = "Myanmar",
                            NumericCode = (short)104
                        },
                        new
                        {
                            Alpha3Code = "NAM",
                            Alpha2Code = "NA",
                            EnglishName = "Namibia",
                            NumericCode = (short)516
                        },
                        new
                        {
                            Alpha3Code = "NRU",
                            Alpha2Code = "NR",
                            EnglishName = "Nauru",
                            NumericCode = (short)520
                        },
                        new
                        {
                            Alpha3Code = "NPL",
                            Alpha2Code = "NP",
                            EnglishName = "Nepal",
                            NumericCode = (short)524
                        },
                        new
                        {
                            Alpha3Code = "NLD",
                            Alpha2Code = "NL",
                            EnglishName = "Netherlands",
                            NumericCode = (short)528
                        },
                        new
                        {
                            Alpha3Code = "NZL",
                            Alpha2Code = "NZ",
                            EnglishName = "New Zealand",
                            NumericCode = (short)554
                        },
                        new
                        {
                            Alpha3Code = "NIC",
                            Alpha2Code = "NI",
                            EnglishName = "Nicaragua",
                            NumericCode = (short)558
                        },
                        new
                        {
                            Alpha3Code = "NER",
                            Alpha2Code = "NE",
                            EnglishName = "Niger",
                            NumericCode = (short)562
                        },
                        new
                        {
                            Alpha3Code = "NGA",
                            Alpha2Code = "NG",
                            EnglishName = "Nigeria",
                            NumericCode = (short)566
                        },
                        new
                        {
                            Alpha3Code = "MKD",
                            Alpha2Code = "MK",
                            EnglishName = "North Macedonia",
                            NumericCode = (short)807
                        },
                        new
                        {
                            Alpha3Code = "NOR",
                            Alpha2Code = "NO",
                            EnglishName = "Norway",
                            NumericCode = (short)578
                        },
                        new
                        {
                            Alpha3Code = "OMN",
                            Alpha2Code = "OM",
                            EnglishName = "Oman",
                            NumericCode = (short)512
                        },
                        new
                        {
                            Alpha3Code = "PAK",
                            Alpha2Code = "PK",
                            EnglishName = "Pakistan",
                            NumericCode = (short)586
                        },
                        new
                        {
                            Alpha3Code = "PLW",
                            Alpha2Code = "PW",
                            EnglishName = "Palau",
                            NumericCode = (short)585
                        },
                        new
                        {
                            Alpha3Code = "PAN",
                            Alpha2Code = "PA",
                            EnglishName = "Panama",
                            NumericCode = (short)591
                        },
                        new
                        {
                            Alpha3Code = "PNG",
                            Alpha2Code = "PG",
                            EnglishName = "Papua New Guinea",
                            NumericCode = (short)598
                        },
                        new
                        {
                            Alpha3Code = "PRY",
                            Alpha2Code = "PY",
                            EnglishName = "Paraguay",
                            NumericCode = (short)600
                        },
                        new
                        {
                            Alpha3Code = "PER",
                            Alpha2Code = "PE",
                            EnglishName = "Peru",
                            NumericCode = (short)604
                        },
                        new
                        {
                            Alpha3Code = "PHL",
                            Alpha2Code = "PH",
                            EnglishName = "Philippines",
                            NumericCode = (short)608
                        },
                        new
                        {
                            Alpha3Code = "POL",
                            Alpha2Code = "PL",
                            EnglishName = "Poland",
                            NumericCode = (short)616
                        },
                        new
                        {
                            Alpha3Code = "PRT",
                            Alpha2Code = "PT",
                            EnglishName = "Portugal",
                            NumericCode = (short)620
                        },
                        new
                        {
                            Alpha3Code = "QAT",
                            Alpha2Code = "QA",
                            EnglishName = "Qatar",
                            NumericCode = (short)634
                        },
                        new
                        {
                            Alpha3Code = "ROU",
                            Alpha2Code = "RO",
                            EnglishName = "Romania",
                            NumericCode = (short)642
                        },
                        new
                        {
                            Alpha3Code = "RUS",
                            Alpha2Code = "RU",
                            EnglishName = "Russian Federation",
                            NumericCode = (short)643
                        },
                        new
                        {
                            Alpha3Code = "RWA",
                            Alpha2Code = "RW",
                            EnglishName = "Rwanda",
                            NumericCode = (short)646
                        },
                        new
                        {
                            Alpha3Code = "KNA",
                            Alpha2Code = "KN",
                            EnglishName = "Saint Kitts and Nevis",
                            NumericCode = (short)659
                        },
                        new
                        {
                            Alpha3Code = "LCA",
                            Alpha2Code = "LC",
                            EnglishName = "Saint Lucia",
                            NumericCode = (short)662
                        },
                        new
                        {
                            Alpha3Code = "VCT",
                            Alpha2Code = "VC",
                            EnglishName = "Saint Vincent and the Grenadines",
                            NumericCode = (short)670
                        },
                        new
                        {
                            Alpha3Code = "WSM",
                            Alpha2Code = "WS",
                            EnglishName = "Samoa",
                            NumericCode = (short)882
                        },
                        new
                        {
                            Alpha3Code = "SMR",
                            Alpha2Code = "SM",
                            EnglishName = "San Marino",
                            NumericCode = (short)674
                        },
                        new
                        {
                            Alpha3Code = "STP",
                            Alpha2Code = "ST",
                            EnglishName = "Sao Tome and Principe",
                            NumericCode = (short)678
                        },
                        new
                        {
                            Alpha3Code = "SAU",
                            Alpha2Code = "SA",
                            EnglishName = "Saudi Arabia",
                            NumericCode = (short)682
                        },
                        new
                        {
                            Alpha3Code = "SEN",
                            Alpha2Code = "SN",
                            EnglishName = "Senegal",
                            NumericCode = (short)686
                        },
                        new
                        {
                            Alpha3Code = "SRB",
                            Alpha2Code = "RS",
                            EnglishName = "Serbia",
                            NumericCode = (short)688
                        },
                        new
                        {
                            Alpha3Code = "SYC",
                            Alpha2Code = "SC",
                            EnglishName = "Seychelles",
                            NumericCode = (short)690
                        },
                        new
                        {
                            Alpha3Code = "SLE",
                            Alpha2Code = "SL",
                            EnglishName = "Sierra Leone",
                            NumericCode = (short)694
                        },
                        new
                        {
                            Alpha3Code = "SGP",
                            Alpha2Code = "SG",
                            EnglishName = "Singapore",
                            NumericCode = (short)702
                        },
                        new
                        {
                            Alpha3Code = "SVK",
                            Alpha2Code = "SK",
                            EnglishName = "Slovakia",
                            NumericCode = (short)703
                        },
                        new
                        {
                            Alpha3Code = "SVN",
                            Alpha2Code = "SI",
                            EnglishName = "Slovenia",
                            NumericCode = (short)705
                        },
                        new
                        {
                            Alpha3Code = "SLB",
                            Alpha2Code = "SB",
                            EnglishName = "Solomon Islands",
                            NumericCode = (short)90
                        },
                        new
                        {
                            Alpha3Code = "SOM",
                            Alpha2Code = "SO",
                            EnglishName = "Somalia",
                            NumericCode = (short)706
                        },
                        new
                        {
                            Alpha3Code = "ZAF",
                            Alpha2Code = "ZA",
                            EnglishName = "South Africa",
                            NumericCode = (short)710
                        },
                        new
                        {
                            Alpha3Code = "SSD",
                            Alpha2Code = "SS",
                            EnglishName = "South Sudan",
                            NumericCode = (short)728
                        },
                        new
                        {
                            Alpha3Code = "ESP",
                            Alpha2Code = "ES",
                            EnglishName = "Spain",
                            NumericCode = (short)724
                        },
                        new
                        {
                            Alpha3Code = "LKA",
                            Alpha2Code = "LK",
                            EnglishName = "Sri Lanka",
                            NumericCode = (short)144
                        },
                        new
                        {
                            Alpha3Code = "SDN",
                            Alpha2Code = "SD",
                            EnglishName = "Sudan",
                            NumericCode = (short)729
                        },
                        new
                        {
                            Alpha3Code = "SUR",
                            Alpha2Code = "SR",
                            EnglishName = "Suriname",
                            NumericCode = (short)740
                        },
                        new
                        {
                            Alpha3Code = "SWE",
                            Alpha2Code = "SE",
                            EnglishName = "Sweden",
                            NumericCode = (short)752
                        },
                        new
                        {
                            Alpha3Code = "CHE",
                            Alpha2Code = "CH",
                            EnglishName = "Switzerland",
                            NumericCode = (short)756
                        },
                        new
                        {
                            Alpha3Code = "SYR",
                            Alpha2Code = "SY",
                            EnglishName = "Syrian Arab Republic",
                            NumericCode = (short)760
                        },
                        new
                        {
                            Alpha3Code = "TJK",
                            Alpha2Code = "TJ",
                            EnglishName = "Tajikistan",
                            NumericCode = (short)762
                        },
                        new
                        {
                            Alpha3Code = "TZA",
                            Alpha2Code = "TZ",
                            EnglishName = "Tanzania, United Republic of",
                            NumericCode = (short)834
                        },
                        new
                        {
                            Alpha3Code = "THA",
                            Alpha2Code = "TH",
                            EnglishName = "Thailand",
                            NumericCode = (short)764
                        },
                        new
                        {
                            Alpha3Code = "TLS",
                            Alpha2Code = "TL",
                            EnglishName = "Timor-Leste",
                            NumericCode = (short)626
                        },
                        new
                        {
                            Alpha3Code = "TGO",
                            Alpha2Code = "TG",
                            EnglishName = "Togo",
                            NumericCode = (short)768
                        },
                        new
                        {
                            Alpha3Code = "TON",
                            Alpha2Code = "TO",
                            EnglishName = "Tonga",
                            NumericCode = (short)776
                        },
                        new
                        {
                            Alpha3Code = "TTO",
                            Alpha2Code = "TT",
                            EnglishName = "Trinidad and Tobago",
                            NumericCode = (short)780
                        },
                        new
                        {
                            Alpha3Code = "TUN",
                            Alpha2Code = "TN",
                            EnglishName = "Tunisia",
                            NumericCode = (short)788
                        },
                        new
                        {
                            Alpha3Code = "TUR",
                            Alpha2Code = "TR",
                            EnglishName = "Türkiye",
                            NumericCode = (short)792
                        },
                        new
                        {
                            Alpha3Code = "TKM",
                            Alpha2Code = "TM",
                            EnglishName = "Turkmenistan",
                            NumericCode = (short)795
                        },
                        new
                        {
                            Alpha3Code = "TUV",
                            Alpha2Code = "TV",
                            EnglishName = "Tuvalu",
                            NumericCode = (short)798
                        },
                        new
                        {
                            Alpha3Code = "UGA",
                            Alpha2Code = "UG",
                            EnglishName = "Uganda",
                            NumericCode = (short)800
                        },
                        new
                        {
                            Alpha3Code = "UKR",
                            Alpha2Code = "UA",
                            EnglishName = "Ukraine",
                            NumericCode = (short)804
                        },
                        new
                        {
                            Alpha3Code = "ARE",
                            Alpha2Code = "AE",
                            EnglishName = "United Arab Emirates",
                            NumericCode = (short)784
                        },
                        new
                        {
                            Alpha3Code = "GBR",
                            Alpha2Code = "GB",
                            EnglishName = "United Kingdom of Great Britain and Northern Ireland",
                            NumericCode = (short)826
                        },
                        new
                        {
                            Alpha3Code = "USA",
                            Alpha2Code = "US",
                            EnglishName = "United States of America",
                            NumericCode = (short)840
                        },
                        new
                        {
                            Alpha3Code = "URY",
                            Alpha2Code = "UY",
                            EnglishName = "Uruguay",
                            NumericCode = (short)858
                        },
                        new
                        {
                            Alpha3Code = "UZB",
                            Alpha2Code = "UZ",
                            EnglishName = "Uzbekistan",
                            NumericCode = (short)860
                        },
                        new
                        {
                            Alpha3Code = "VUT",
                            Alpha2Code = "VU",
                            EnglishName = "Vanuatu",
                            NumericCode = (short)548
                        },
                        new
                        {
                            Alpha3Code = "VEN",
                            Alpha2Code = "VE",
                            EnglishName = "Venezuela, Bolivarian Republic of",
                            NumericCode = (short)862
                        },
                        new
                        {
                            Alpha3Code = "VNM",
                            Alpha2Code = "VN",
                            EnglishName = "Viet Nam",
                            NumericCode = (short)704
                        },
                        new
                        {
                            Alpha3Code = "YEM",
                            Alpha2Code = "YE",
                            EnglishName = "Yemen",
                            NumericCode = (short)887
                        },
                        new
                        {
                            Alpha3Code = "ZMB",
                            Alpha2Code = "ZM",
                            EnglishName = "Zambia",
                            NumericCode = (short)894
                        },
                        new
                        {
                            Alpha3Code = "ZWE",
                            Alpha2Code = "ZW",
                            EnglishName = "Zimbabwe",
                            NumericCode = (short)716
                        });
                });

            modelBuilder.Entity("BankDataDb.Entities.Currency", b =>
                {
                    b.Property<string>("CurrencyCode")
                        .HasColumnType("char(3)")
                        .HasAnnotation("Relational:JsonPropertyName", "code");

                    b.Property<byte>("MinorUnitFractions")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "decimal_digits");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("CurrencyCode");

                    b.HasIndex("CurrencyCode")
                        .IsUnique();

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            CurrencyCode = "USD",
                            MinorUnitFractions = (byte)2,
                            Name = "US Dollar"
                        },
                        new
                        {
                            CurrencyCode = "CAD",
                            MinorUnitFractions = (byte)2,
                            Name = "Canadian Dollar"
                        },
                        new
                        {
                            CurrencyCode = "EUR",
                            MinorUnitFractions = (byte)2,
                            Name = "Euro"
                        },
                        new
                        {
                            CurrencyCode = "AED",
                            MinorUnitFractions = (byte)2,
                            Name = "United Arab Emirates Dirham"
                        },
                        new
                        {
                            CurrencyCode = "AFN",
                            MinorUnitFractions = (byte)0,
                            Name = "Afghan Afghani"
                        },
                        new
                        {
                            CurrencyCode = "ALL",
                            MinorUnitFractions = (byte)0,
                            Name = "Albanian Lek"
                        },
                        new
                        {
                            CurrencyCode = "AMD",
                            MinorUnitFractions = (byte)0,
                            Name = "Armenian Dram"
                        },
                        new
                        {
                            CurrencyCode = "ARS",
                            MinorUnitFractions = (byte)2,
                            Name = "Argentine Peso"
                        },
                        new
                        {
                            CurrencyCode = "AUD",
                            MinorUnitFractions = (byte)2,
                            Name = "Australian Dollar"
                        },
                        new
                        {
                            CurrencyCode = "AZN",
                            MinorUnitFractions = (byte)2,
                            Name = "Azerbaijani Manat"
                        },
                        new
                        {
                            CurrencyCode = "BAM",
                            MinorUnitFractions = (byte)2,
                            Name = "Bosnia-Herzegovina Convertible Mark"
                        },
                        new
                        {
                            CurrencyCode = "BDT",
                            MinorUnitFractions = (byte)2,
                            Name = "Bangladeshi Taka"
                        },
                        new
                        {
                            CurrencyCode = "BGN",
                            MinorUnitFractions = (byte)2,
                            Name = "Bulgarian Lev"
                        },
                        new
                        {
                            CurrencyCode = "BHD",
                            MinorUnitFractions = (byte)3,
                            Name = "Bahraini Dinar"
                        },
                        new
                        {
                            CurrencyCode = "BIF",
                            MinorUnitFractions = (byte)0,
                            Name = "Burundian Franc"
                        },
                        new
                        {
                            CurrencyCode = "BND",
                            MinorUnitFractions = (byte)2,
                            Name = "Brunei Dollar"
                        },
                        new
                        {
                            CurrencyCode = "BOB",
                            MinorUnitFractions = (byte)2,
                            Name = "Bolivian Boliviano"
                        },
                        new
                        {
                            CurrencyCode = "BRL",
                            MinorUnitFractions = (byte)2,
                            Name = "Brazilian Real"
                        },
                        new
                        {
                            CurrencyCode = "BWP",
                            MinorUnitFractions = (byte)2,
                            Name = "Botswanan Pula"
                        },
                        new
                        {
                            CurrencyCode = "BYN",
                            MinorUnitFractions = (byte)2,
                            Name = "Belarusian Ruble"
                        },
                        new
                        {
                            CurrencyCode = "BZD",
                            MinorUnitFractions = (byte)2,
                            Name = "Belize Dollar"
                        },
                        new
                        {
                            CurrencyCode = "CDF",
                            MinorUnitFractions = (byte)2,
                            Name = "Congolese Franc"
                        },
                        new
                        {
                            CurrencyCode = "CHF",
                            MinorUnitFractions = (byte)2,
                            Name = "Swiss Franc"
                        },
                        new
                        {
                            CurrencyCode = "CLP",
                            MinorUnitFractions = (byte)0,
                            Name = "Chilean Peso"
                        },
                        new
                        {
                            CurrencyCode = "CNY",
                            MinorUnitFractions = (byte)2,
                            Name = "Chinese Yuan"
                        },
                        new
                        {
                            CurrencyCode = "COP",
                            MinorUnitFractions = (byte)0,
                            Name = "Colombian Peso"
                        },
                        new
                        {
                            CurrencyCode = "CRC",
                            MinorUnitFractions = (byte)0,
                            Name = "Costa Rican Colón"
                        },
                        new
                        {
                            CurrencyCode = "CVE",
                            MinorUnitFractions = (byte)2,
                            Name = "Cape Verdean Escudo"
                        },
                        new
                        {
                            CurrencyCode = "CZK",
                            MinorUnitFractions = (byte)2,
                            Name = "Czech Republic Koruna"
                        },
                        new
                        {
                            CurrencyCode = "DJF",
                            MinorUnitFractions = (byte)0,
                            Name = "Djiboutian Franc"
                        },
                        new
                        {
                            CurrencyCode = "DKK",
                            MinorUnitFractions = (byte)2,
                            Name = "Danish Krone"
                        },
                        new
                        {
                            CurrencyCode = "DOP",
                            MinorUnitFractions = (byte)2,
                            Name = "Dominican Peso"
                        },
                        new
                        {
                            CurrencyCode = "DZD",
                            MinorUnitFractions = (byte)2,
                            Name = "Algerian Dinar"
                        },
                        new
                        {
                            CurrencyCode = "EEK",
                            MinorUnitFractions = (byte)2,
                            Name = "Estonian Kroon"
                        },
                        new
                        {
                            CurrencyCode = "EGP",
                            MinorUnitFractions = (byte)2,
                            Name = "Egyptian Pound"
                        },
                        new
                        {
                            CurrencyCode = "ERN",
                            MinorUnitFractions = (byte)2,
                            Name = "Eritrean Nakfa"
                        },
                        new
                        {
                            CurrencyCode = "ETB",
                            MinorUnitFractions = (byte)2,
                            Name = "Ethiopian Birr"
                        },
                        new
                        {
                            CurrencyCode = "GBP",
                            MinorUnitFractions = (byte)2,
                            Name = "British Pound Sterling"
                        },
                        new
                        {
                            CurrencyCode = "GEL",
                            MinorUnitFractions = (byte)2,
                            Name = "Georgian Lari"
                        },
                        new
                        {
                            CurrencyCode = "GHS",
                            MinorUnitFractions = (byte)2,
                            Name = "Ghanaian Cedi"
                        },
                        new
                        {
                            CurrencyCode = "GNF",
                            MinorUnitFractions = (byte)0,
                            Name = "Guinean Franc"
                        },
                        new
                        {
                            CurrencyCode = "GTQ",
                            MinorUnitFractions = (byte)2,
                            Name = "Guatemalan Quetzal"
                        },
                        new
                        {
                            CurrencyCode = "HKD",
                            MinorUnitFractions = (byte)2,
                            Name = "Hong Kong Dollar"
                        },
                        new
                        {
                            CurrencyCode = "HNL",
                            MinorUnitFractions = (byte)2,
                            Name = "Honduran Lempira"
                        },
                        new
                        {
                            CurrencyCode = "HRK",
                            MinorUnitFractions = (byte)2,
                            Name = "Croatian Kuna"
                        },
                        new
                        {
                            CurrencyCode = "HUF",
                            MinorUnitFractions = (byte)0,
                            Name = "Hungarian Forint"
                        },
                        new
                        {
                            CurrencyCode = "IDR",
                            MinorUnitFractions = (byte)0,
                            Name = "Indonesian Rupiah"
                        },
                        new
                        {
                            CurrencyCode = "ILS",
                            MinorUnitFractions = (byte)2,
                            Name = "Israeli New Sheqel"
                        },
                        new
                        {
                            CurrencyCode = "INR",
                            MinorUnitFractions = (byte)2,
                            Name = "Indian Rupee"
                        },
                        new
                        {
                            CurrencyCode = "IQD",
                            MinorUnitFractions = (byte)0,
                            Name = "Iraqi Dinar"
                        },
                        new
                        {
                            CurrencyCode = "IRR",
                            MinorUnitFractions = (byte)0,
                            Name = "Iranian Rial"
                        },
                        new
                        {
                            CurrencyCode = "ISK",
                            MinorUnitFractions = (byte)0,
                            Name = "Icelandic Króna"
                        },
                        new
                        {
                            CurrencyCode = "JMD",
                            MinorUnitFractions = (byte)2,
                            Name = "Jamaican Dollar"
                        },
                        new
                        {
                            CurrencyCode = "JOD",
                            MinorUnitFractions = (byte)3,
                            Name = "Jordanian Dinar"
                        },
                        new
                        {
                            CurrencyCode = "JPY",
                            MinorUnitFractions = (byte)0,
                            Name = "Japanese Yen"
                        },
                        new
                        {
                            CurrencyCode = "KES",
                            MinorUnitFractions = (byte)2,
                            Name = "Kenyan Shilling"
                        },
                        new
                        {
                            CurrencyCode = "KHR",
                            MinorUnitFractions = (byte)2,
                            Name = "Cambodian Riel"
                        },
                        new
                        {
                            CurrencyCode = "KMF",
                            MinorUnitFractions = (byte)0,
                            Name = "Comorian Franc"
                        },
                        new
                        {
                            CurrencyCode = "KRW",
                            MinorUnitFractions = (byte)0,
                            Name = "South Korean Won"
                        },
                        new
                        {
                            CurrencyCode = "KWD",
                            MinorUnitFractions = (byte)3,
                            Name = "Kuwaiti Dinar"
                        },
                        new
                        {
                            CurrencyCode = "KZT",
                            MinorUnitFractions = (byte)2,
                            Name = "Kazakhstani Tenge"
                        },
                        new
                        {
                            CurrencyCode = "LBP",
                            MinorUnitFractions = (byte)0,
                            Name = "Lebanese Pound"
                        },
                        new
                        {
                            CurrencyCode = "LKR",
                            MinorUnitFractions = (byte)2,
                            Name = "Sri Lankan Rupee"
                        },
                        new
                        {
                            CurrencyCode = "LTL",
                            MinorUnitFractions = (byte)2,
                            Name = "Lithuanian Litas"
                        },
                        new
                        {
                            CurrencyCode = "LVL",
                            MinorUnitFractions = (byte)2,
                            Name = "Latvian Lats"
                        },
                        new
                        {
                            CurrencyCode = "LYD",
                            MinorUnitFractions = (byte)3,
                            Name = "Libyan Dinar"
                        },
                        new
                        {
                            CurrencyCode = "MAD",
                            MinorUnitFractions = (byte)2,
                            Name = "Moroccan Dirham"
                        },
                        new
                        {
                            CurrencyCode = "MDL",
                            MinorUnitFractions = (byte)2,
                            Name = "Moldovan Leu"
                        },
                        new
                        {
                            CurrencyCode = "MGA",
                            MinorUnitFractions = (byte)0,
                            Name = "Malagasy Ariary"
                        },
                        new
                        {
                            CurrencyCode = "MKD",
                            MinorUnitFractions = (byte)2,
                            Name = "Macedonian Denar"
                        },
                        new
                        {
                            CurrencyCode = "MMK",
                            MinorUnitFractions = (byte)0,
                            Name = "Myanma Kyat"
                        },
                        new
                        {
                            CurrencyCode = "MOP",
                            MinorUnitFractions = (byte)2,
                            Name = "Macanese Pataca"
                        },
                        new
                        {
                            CurrencyCode = "MUR",
                            MinorUnitFractions = (byte)0,
                            Name = "Mauritian Rupee"
                        },
                        new
                        {
                            CurrencyCode = "MXN",
                            MinorUnitFractions = (byte)2,
                            Name = "Mexican Peso"
                        },
                        new
                        {
                            CurrencyCode = "MYR",
                            MinorUnitFractions = (byte)2,
                            Name = "Malaysian Ringgit"
                        },
                        new
                        {
                            CurrencyCode = "MZN",
                            MinorUnitFractions = (byte)2,
                            Name = "Mozambican Metical"
                        },
                        new
                        {
                            CurrencyCode = "NAD",
                            MinorUnitFractions = (byte)2,
                            Name = "Namibian Dollar"
                        },
                        new
                        {
                            CurrencyCode = "NGN",
                            MinorUnitFractions = (byte)2,
                            Name = "Nigerian Naira"
                        },
                        new
                        {
                            CurrencyCode = "NIO",
                            MinorUnitFractions = (byte)2,
                            Name = "Nicaraguan Córdoba"
                        },
                        new
                        {
                            CurrencyCode = "NOK",
                            MinorUnitFractions = (byte)2,
                            Name = "Norwegian Krone"
                        },
                        new
                        {
                            CurrencyCode = "NPR",
                            MinorUnitFractions = (byte)2,
                            Name = "Nepalese Rupee"
                        },
                        new
                        {
                            CurrencyCode = "NZD",
                            MinorUnitFractions = (byte)2,
                            Name = "New Zealand Dollar"
                        },
                        new
                        {
                            CurrencyCode = "OMR",
                            MinorUnitFractions = (byte)3,
                            Name = "Omani Rial"
                        },
                        new
                        {
                            CurrencyCode = "PAB",
                            MinorUnitFractions = (byte)2,
                            Name = "Panamanian Balboa"
                        },
                        new
                        {
                            CurrencyCode = "PEN",
                            MinorUnitFractions = (byte)2,
                            Name = "Peruvian Nuevo Sol"
                        },
                        new
                        {
                            CurrencyCode = "PHP",
                            MinorUnitFractions = (byte)2,
                            Name = "Philippine Peso"
                        },
                        new
                        {
                            CurrencyCode = "PKR",
                            MinorUnitFractions = (byte)0,
                            Name = "Pakistani Rupee"
                        },
                        new
                        {
                            CurrencyCode = "PLN",
                            MinorUnitFractions = (byte)2,
                            Name = "Polish Zloty"
                        },
                        new
                        {
                            CurrencyCode = "PYG",
                            MinorUnitFractions = (byte)0,
                            Name = "Paraguayan Guarani"
                        },
                        new
                        {
                            CurrencyCode = "QAR",
                            MinorUnitFractions = (byte)2,
                            Name = "Qatari Rial"
                        },
                        new
                        {
                            CurrencyCode = "RON",
                            MinorUnitFractions = (byte)2,
                            Name = "Romanian Leu"
                        },
                        new
                        {
                            CurrencyCode = "RSD",
                            MinorUnitFractions = (byte)0,
                            Name = "Serbian Dinar"
                        },
                        new
                        {
                            CurrencyCode = "RUB",
                            MinorUnitFractions = (byte)2,
                            Name = "Russian Ruble"
                        },
                        new
                        {
                            CurrencyCode = "RWF",
                            MinorUnitFractions = (byte)0,
                            Name = "Rwandan Franc"
                        },
                        new
                        {
                            CurrencyCode = "SAR",
                            MinorUnitFractions = (byte)2,
                            Name = "Saudi Riyal"
                        },
                        new
                        {
                            CurrencyCode = "SDG",
                            MinorUnitFractions = (byte)2,
                            Name = "Sudanese Pound"
                        },
                        new
                        {
                            CurrencyCode = "SEK",
                            MinorUnitFractions = (byte)2,
                            Name = "Swedish Krona"
                        },
                        new
                        {
                            CurrencyCode = "SGD",
                            MinorUnitFractions = (byte)2,
                            Name = "Singapore Dollar"
                        },
                        new
                        {
                            CurrencyCode = "SOS",
                            MinorUnitFractions = (byte)0,
                            Name = "Somali Shilling"
                        },
                        new
                        {
                            CurrencyCode = "SYP",
                            MinorUnitFractions = (byte)0,
                            Name = "Syrian Pound"
                        },
                        new
                        {
                            CurrencyCode = "THB",
                            MinorUnitFractions = (byte)2,
                            Name = "Thai Baht"
                        },
                        new
                        {
                            CurrencyCode = "TND",
                            MinorUnitFractions = (byte)3,
                            Name = "Tunisian Dinar"
                        },
                        new
                        {
                            CurrencyCode = "TOP",
                            MinorUnitFractions = (byte)2,
                            Name = "Tongan Paʻanga"
                        },
                        new
                        {
                            CurrencyCode = "TRY",
                            MinorUnitFractions = (byte)2,
                            Name = "Turkish Lira"
                        },
                        new
                        {
                            CurrencyCode = "TTD",
                            MinorUnitFractions = (byte)2,
                            Name = "Trinidad and Tobago Dollar"
                        },
                        new
                        {
                            CurrencyCode = "TWD",
                            MinorUnitFractions = (byte)2,
                            Name = "New Taiwan Dollar"
                        },
                        new
                        {
                            CurrencyCode = "TZS",
                            MinorUnitFractions = (byte)0,
                            Name = "Tanzanian Shilling"
                        },
                        new
                        {
                            CurrencyCode = "UAH",
                            MinorUnitFractions = (byte)2,
                            Name = "Ukrainian Hryvnia"
                        },
                        new
                        {
                            CurrencyCode = "UGX",
                            MinorUnitFractions = (byte)0,
                            Name = "Ugandan Shilling"
                        },
                        new
                        {
                            CurrencyCode = "UYU",
                            MinorUnitFractions = (byte)2,
                            Name = "Uruguayan Peso"
                        },
                        new
                        {
                            CurrencyCode = "UZS",
                            MinorUnitFractions = (byte)0,
                            Name = "Uzbekistan Som"
                        },
                        new
                        {
                            CurrencyCode = "VEF",
                            MinorUnitFractions = (byte)2,
                            Name = "Venezuelan Bolívar"
                        },
                        new
                        {
                            CurrencyCode = "VND",
                            MinorUnitFractions = (byte)0,
                            Name = "Vietnamese Dong"
                        },
                        new
                        {
                            CurrencyCode = "XAF",
                            MinorUnitFractions = (byte)0,
                            Name = "CFA Franc BEAC"
                        },
                        new
                        {
                            CurrencyCode = "XOF",
                            MinorUnitFractions = (byte)0,
                            Name = "CFA Franc BCEAO"
                        },
                        new
                        {
                            CurrencyCode = "YER",
                            MinorUnitFractions = (byte)0,
                            Name = "Yemeni Rial"
                        },
                        new
                        {
                            CurrencyCode = "ZAR",
                            MinorUnitFractions = (byte)2,
                            Name = "South African Rand"
                        },
                        new
                        {
                            CurrencyCode = "ZMK",
                            MinorUnitFractions = (byte)0,
                            Name = "Zambian Kwacha"
                        },
                        new
                        {
                            CurrencyCode = "ZWL",
                            MinorUnitFractions = (byte)0,
                            Name = "Zimbabwean Dollar"
                        });
                });

            modelBuilder.Entity("BankDataDb.Entities.Card", b =>
                {
                    b.HasOne("BankDataDb.Entities.Bank", "IssuedBank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IssuedBank");
                });

            modelBuilder.Entity("BankDataDb.Entities.CardTransaction", b =>
                {
                    b.HasOne("BankDataDb.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryAlpha3Code");

                    b.HasOne("BankDataDb.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Currency");
                });
#pragma warning restore 612, 618
        }
    }
}
