// <auto-generated />
using System;
using BankDataDb.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankDataDb.Migrations
{
    [DbContext(typeof(BankDataContext))]
    partial class BankDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("BankDataDb.Entities.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("BankDataDb.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BankId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardType")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("BankDataDb.Entities.CardTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountInMinorUnit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryAlpha3Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("TransactionTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryAlpha3Code");

                    b.HasIndex("CurrencyCode");

                    b.ToTable("CardTransactions");
                });

            modelBuilder.Entity("BankDataDb.Entities.Country", b =>
                {
                    b.Property<string>("Alpha3Code")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "alpha3");

                    b.Property<string>("Alpha2Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "alpha2");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<short>("NumericCode")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.HasKey("Alpha3Code");

                    b.HasIndex("Alpha2Code")
                        .IsUnique();

                    b.HasIndex("Alpha3Code")
                        .IsUnique();

                    b.HasIndex("NumericCode")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Alpha3Code = "afg",
                            Alpha2Code = "af",
                            EnglishName = "Afghanistan",
                            NumericCode = (short)4
                        },
                        new
                        {
                            Alpha3Code = "alb",
                            Alpha2Code = "al",
                            EnglishName = "Albania",
                            NumericCode = (short)8
                        },
                        new
                        {
                            Alpha3Code = "dza",
                            Alpha2Code = "dz",
                            EnglishName = "Algeria",
                            NumericCode = (short)12
                        },
                        new
                        {
                            Alpha3Code = "and",
                            Alpha2Code = "ad",
                            EnglishName = "Andorra",
                            NumericCode = (short)20
                        },
                        new
                        {
                            Alpha3Code = "ago",
                            Alpha2Code = "ao",
                            EnglishName = "Angola",
                            NumericCode = (short)24
                        },
                        new
                        {
                            Alpha3Code = "atg",
                            Alpha2Code = "ag",
                            EnglishName = "Antigua and Barbuda",
                            NumericCode = (short)28
                        },
                        new
                        {
                            Alpha3Code = "arg",
                            Alpha2Code = "ar",
                            EnglishName = "Argentina",
                            NumericCode = (short)32
                        },
                        new
                        {
                            Alpha3Code = "arm",
                            Alpha2Code = "am",
                            EnglishName = "Armenia",
                            NumericCode = (short)51
                        },
                        new
                        {
                            Alpha3Code = "aus",
                            Alpha2Code = "au",
                            EnglishName = "Australia",
                            NumericCode = (short)36
                        },
                        new
                        {
                            Alpha3Code = "aut",
                            Alpha2Code = "at",
                            EnglishName = "Austria",
                            NumericCode = (short)40
                        },
                        new
                        {
                            Alpha3Code = "aze",
                            Alpha2Code = "az",
                            EnglishName = "Azerbaijan",
                            NumericCode = (short)31
                        },
                        new
                        {
                            Alpha3Code = "bhs",
                            Alpha2Code = "bs",
                            EnglishName = "Bahamas",
                            NumericCode = (short)44
                        },
                        new
                        {
                            Alpha3Code = "bhr",
                            Alpha2Code = "bh",
                            EnglishName = "Bahrain",
                            NumericCode = (short)48
                        },
                        new
                        {
                            Alpha3Code = "bgd",
                            Alpha2Code = "bd",
                            EnglishName = "Bangladesh",
                            NumericCode = (short)50
                        },
                        new
                        {
                            Alpha3Code = "brb",
                            Alpha2Code = "bb",
                            EnglishName = "Barbados",
                            NumericCode = (short)52
                        },
                        new
                        {
                            Alpha3Code = "blr",
                            Alpha2Code = "by",
                            EnglishName = "Belarus",
                            NumericCode = (short)112
                        },
                        new
                        {
                            Alpha3Code = "bel",
                            Alpha2Code = "be",
                            EnglishName = "Belgium",
                            NumericCode = (short)56
                        },
                        new
                        {
                            Alpha3Code = "blz",
                            Alpha2Code = "bz",
                            EnglishName = "Belize",
                            NumericCode = (short)84
                        },
                        new
                        {
                            Alpha3Code = "ben",
                            Alpha2Code = "bj",
                            EnglishName = "Benin",
                            NumericCode = (short)204
                        },
                        new
                        {
                            Alpha3Code = "btn",
                            Alpha2Code = "bt",
                            EnglishName = "Bhutan",
                            NumericCode = (short)64
                        },
                        new
                        {
                            Alpha3Code = "bol",
                            Alpha2Code = "bo",
                            EnglishName = "Bolivia, Plurinational State of",
                            NumericCode = (short)68
                        },
                        new
                        {
                            Alpha3Code = "bih",
                            Alpha2Code = "ba",
                            EnglishName = "Bosnia and Herzegovina",
                            NumericCode = (short)70
                        },
                        new
                        {
                            Alpha3Code = "bwa",
                            Alpha2Code = "bw",
                            EnglishName = "Botswana",
                            NumericCode = (short)72
                        },
                        new
                        {
                            Alpha3Code = "bra",
                            Alpha2Code = "br",
                            EnglishName = "Brazil",
                            NumericCode = (short)76
                        },
                        new
                        {
                            Alpha3Code = "brn",
                            Alpha2Code = "bn",
                            EnglishName = "Brunei Darussalam",
                            NumericCode = (short)96
                        },
                        new
                        {
                            Alpha3Code = "bgr",
                            Alpha2Code = "bg",
                            EnglishName = "Bulgaria",
                            NumericCode = (short)100
                        },
                        new
                        {
                            Alpha3Code = "bfa",
                            Alpha2Code = "bf",
                            EnglishName = "Burkina Faso",
                            NumericCode = (short)854
                        },
                        new
                        {
                            Alpha3Code = "bdi",
                            Alpha2Code = "bi",
                            EnglishName = "Burundi",
                            NumericCode = (short)108
                        },
                        new
                        {
                            Alpha3Code = "cpv",
                            Alpha2Code = "cv",
                            EnglishName = "Cabo Verde",
                            NumericCode = (short)132
                        },
                        new
                        {
                            Alpha3Code = "khm",
                            Alpha2Code = "kh",
                            EnglishName = "Cambodia",
                            NumericCode = (short)116
                        },
                        new
                        {
                            Alpha3Code = "cmr",
                            Alpha2Code = "cm",
                            EnglishName = "Cameroon",
                            NumericCode = (short)120
                        },
                        new
                        {
                            Alpha3Code = "can",
                            Alpha2Code = "ca",
                            EnglishName = "Canada",
                            NumericCode = (short)124
                        },
                        new
                        {
                            Alpha3Code = "caf",
                            Alpha2Code = "cf",
                            EnglishName = "Central African Republic",
                            NumericCode = (short)140
                        },
                        new
                        {
                            Alpha3Code = "tcd",
                            Alpha2Code = "td",
                            EnglishName = "Chad",
                            NumericCode = (short)148
                        },
                        new
                        {
                            Alpha3Code = "chl",
                            Alpha2Code = "cl",
                            EnglishName = "Chile",
                            NumericCode = (short)152
                        },
                        new
                        {
                            Alpha3Code = "chn",
                            Alpha2Code = "cn",
                            EnglishName = "China",
                            NumericCode = (short)156
                        },
                        new
                        {
                            Alpha3Code = "col",
                            Alpha2Code = "co",
                            EnglishName = "Colombia",
                            NumericCode = (short)170
                        },
                        new
                        {
                            Alpha3Code = "com",
                            Alpha2Code = "km",
                            EnglishName = "Comoros",
                            NumericCode = (short)174
                        },
                        new
                        {
                            Alpha3Code = "cog",
                            Alpha2Code = "cg",
                            EnglishName = "Congo",
                            NumericCode = (short)178
                        },
                        new
                        {
                            Alpha3Code = "cod",
                            Alpha2Code = "cd",
                            EnglishName = "Congo, Democratic Republic of the",
                            NumericCode = (short)180
                        },
                        new
                        {
                            Alpha3Code = "cri",
                            Alpha2Code = "cr",
                            EnglishName = "Costa Rica",
                            NumericCode = (short)188
                        },
                        new
                        {
                            Alpha3Code = "civ",
                            Alpha2Code = "ci",
                            EnglishName = "Côte d'Ivoire",
                            NumericCode = (short)384
                        },
                        new
                        {
                            Alpha3Code = "hrv",
                            Alpha2Code = "hr",
                            EnglishName = "Croatia",
                            NumericCode = (short)191
                        },
                        new
                        {
                            Alpha3Code = "cub",
                            Alpha2Code = "cu",
                            EnglishName = "Cuba",
                            NumericCode = (short)192
                        },
                        new
                        {
                            Alpha3Code = "cyp",
                            Alpha2Code = "cy",
                            EnglishName = "Cyprus",
                            NumericCode = (short)196
                        },
                        new
                        {
                            Alpha3Code = "cze",
                            Alpha2Code = "cz",
                            EnglishName = "Czechia",
                            NumericCode = (short)203
                        },
                        new
                        {
                            Alpha3Code = "dnk",
                            Alpha2Code = "dk",
                            EnglishName = "Denmark",
                            NumericCode = (short)208
                        },
                        new
                        {
                            Alpha3Code = "dji",
                            Alpha2Code = "dj",
                            EnglishName = "Djibouti",
                            NumericCode = (short)262
                        },
                        new
                        {
                            Alpha3Code = "dma",
                            Alpha2Code = "dm",
                            EnglishName = "Dominica",
                            NumericCode = (short)212
                        },
                        new
                        {
                            Alpha3Code = "dom",
                            Alpha2Code = "do",
                            EnglishName = "Dominican Republic",
                            NumericCode = (short)214
                        },
                        new
                        {
                            Alpha3Code = "ecu",
                            Alpha2Code = "ec",
                            EnglishName = "Ecuador",
                            NumericCode = (short)218
                        },
                        new
                        {
                            Alpha3Code = "egy",
                            Alpha2Code = "eg",
                            EnglishName = "Egypt",
                            NumericCode = (short)818
                        },
                        new
                        {
                            Alpha3Code = "slv",
                            Alpha2Code = "sv",
                            EnglishName = "El Salvador",
                            NumericCode = (short)222
                        },
                        new
                        {
                            Alpha3Code = "gnq",
                            Alpha2Code = "gq",
                            EnglishName = "Equatorial Guinea",
                            NumericCode = (short)226
                        },
                        new
                        {
                            Alpha3Code = "eri",
                            Alpha2Code = "er",
                            EnglishName = "Eritrea",
                            NumericCode = (short)232
                        },
                        new
                        {
                            Alpha3Code = "est",
                            Alpha2Code = "ee",
                            EnglishName = "Estonia",
                            NumericCode = (short)233
                        },
                        new
                        {
                            Alpha3Code = "swz",
                            Alpha2Code = "sz",
                            EnglishName = "Eswatini",
                            NumericCode = (short)748
                        },
                        new
                        {
                            Alpha3Code = "eth",
                            Alpha2Code = "et",
                            EnglishName = "Ethiopia",
                            NumericCode = (short)231
                        },
                        new
                        {
                            Alpha3Code = "fji",
                            Alpha2Code = "fj",
                            EnglishName = "Fiji",
                            NumericCode = (short)242
                        },
                        new
                        {
                            Alpha3Code = "fin",
                            Alpha2Code = "fi",
                            EnglishName = "Finland",
                            NumericCode = (short)246
                        },
                        new
                        {
                            Alpha3Code = "fra",
                            Alpha2Code = "fr",
                            EnglishName = "France",
                            NumericCode = (short)250
                        },
                        new
                        {
                            Alpha3Code = "gab",
                            Alpha2Code = "ga",
                            EnglishName = "Gabon",
                            NumericCode = (short)266
                        },
                        new
                        {
                            Alpha3Code = "gmb",
                            Alpha2Code = "gm",
                            EnglishName = "Gambia",
                            NumericCode = (short)270
                        },
                        new
                        {
                            Alpha3Code = "geo",
                            Alpha2Code = "ge",
                            EnglishName = "Georgia",
                            NumericCode = (short)268
                        },
                        new
                        {
                            Alpha3Code = "deu",
                            Alpha2Code = "de",
                            EnglishName = "Germany",
                            NumericCode = (short)276
                        },
                        new
                        {
                            Alpha3Code = "gha",
                            Alpha2Code = "gh",
                            EnglishName = "Ghana",
                            NumericCode = (short)288
                        },
                        new
                        {
                            Alpha3Code = "grc",
                            Alpha2Code = "gr",
                            EnglishName = "Greece",
                            NumericCode = (short)300
                        },
                        new
                        {
                            Alpha3Code = "grd",
                            Alpha2Code = "gd",
                            EnglishName = "Grenada",
                            NumericCode = (short)308
                        },
                        new
                        {
                            Alpha3Code = "gtm",
                            Alpha2Code = "gt",
                            EnglishName = "Guatemala",
                            NumericCode = (short)320
                        },
                        new
                        {
                            Alpha3Code = "gin",
                            Alpha2Code = "gn",
                            EnglishName = "Guinea",
                            NumericCode = (short)324
                        },
                        new
                        {
                            Alpha3Code = "gnb",
                            Alpha2Code = "gw",
                            EnglishName = "Guinea-Bissau",
                            NumericCode = (short)624
                        },
                        new
                        {
                            Alpha3Code = "guy",
                            Alpha2Code = "gy",
                            EnglishName = "Guyana",
                            NumericCode = (short)328
                        },
                        new
                        {
                            Alpha3Code = "hti",
                            Alpha2Code = "ht",
                            EnglishName = "Haiti",
                            NumericCode = (short)332
                        },
                        new
                        {
                            Alpha3Code = "hnd",
                            Alpha2Code = "hn",
                            EnglishName = "Honduras",
                            NumericCode = (short)340
                        },
                        new
                        {
                            Alpha3Code = "hun",
                            Alpha2Code = "hu",
                            EnglishName = "Hungary",
                            NumericCode = (short)348
                        },
                        new
                        {
                            Alpha3Code = "isl",
                            Alpha2Code = "is",
                            EnglishName = "Iceland",
                            NumericCode = (short)352
                        },
                        new
                        {
                            Alpha3Code = "ind",
                            Alpha2Code = "in",
                            EnglishName = "India",
                            NumericCode = (short)356
                        },
                        new
                        {
                            Alpha3Code = "idn",
                            Alpha2Code = "id",
                            EnglishName = "Indonesia",
                            NumericCode = (short)360
                        },
                        new
                        {
                            Alpha3Code = "irn",
                            Alpha2Code = "ir",
                            EnglishName = "Iran, Islamic Republic of",
                            NumericCode = (short)364
                        },
                        new
                        {
                            Alpha3Code = "irq",
                            Alpha2Code = "iq",
                            EnglishName = "Iraq",
                            NumericCode = (short)368
                        },
                        new
                        {
                            Alpha3Code = "irl",
                            Alpha2Code = "ie",
                            EnglishName = "Ireland",
                            NumericCode = (short)372
                        },
                        new
                        {
                            Alpha3Code = "isr",
                            Alpha2Code = "il",
                            EnglishName = "Israel",
                            NumericCode = (short)376
                        },
                        new
                        {
                            Alpha3Code = "ita",
                            Alpha2Code = "it",
                            EnglishName = "Italy",
                            NumericCode = (short)380
                        },
                        new
                        {
                            Alpha3Code = "jam",
                            Alpha2Code = "jm",
                            EnglishName = "Jamaica",
                            NumericCode = (short)388
                        },
                        new
                        {
                            Alpha3Code = "jpn",
                            Alpha2Code = "jp",
                            EnglishName = "Japan",
                            NumericCode = (short)392
                        },
                        new
                        {
                            Alpha3Code = "jor",
                            Alpha2Code = "jo",
                            EnglishName = "Jordan",
                            NumericCode = (short)400
                        },
                        new
                        {
                            Alpha3Code = "kaz",
                            Alpha2Code = "kz",
                            EnglishName = "Kazakhstan",
                            NumericCode = (short)398
                        },
                        new
                        {
                            Alpha3Code = "ken",
                            Alpha2Code = "ke",
                            EnglishName = "Kenya",
                            NumericCode = (short)404
                        },
                        new
                        {
                            Alpha3Code = "kir",
                            Alpha2Code = "ki",
                            EnglishName = "Kiribati",
                            NumericCode = (short)296
                        },
                        new
                        {
                            Alpha3Code = "prk",
                            Alpha2Code = "kp",
                            EnglishName = "Korea, Democratic People's Republic of",
                            NumericCode = (short)408
                        },
                        new
                        {
                            Alpha3Code = "kor",
                            Alpha2Code = "kr",
                            EnglishName = "Korea, Republic of",
                            NumericCode = (short)410
                        },
                        new
                        {
                            Alpha3Code = "kwt",
                            Alpha2Code = "kw",
                            EnglishName = "Kuwait",
                            NumericCode = (short)414
                        },
                        new
                        {
                            Alpha3Code = "kgz",
                            Alpha2Code = "kg",
                            EnglishName = "Kyrgyzstan",
                            NumericCode = (short)417
                        },
                        new
                        {
                            Alpha3Code = "lao",
                            Alpha2Code = "la",
                            EnglishName = "Lao People's Democratic Republic",
                            NumericCode = (short)418
                        },
                        new
                        {
                            Alpha3Code = "lva",
                            Alpha2Code = "lv",
                            EnglishName = "Latvia",
                            NumericCode = (short)428
                        },
                        new
                        {
                            Alpha3Code = "lbn",
                            Alpha2Code = "lb",
                            EnglishName = "Lebanon",
                            NumericCode = (short)422
                        },
                        new
                        {
                            Alpha3Code = "lso",
                            Alpha2Code = "ls",
                            EnglishName = "Lesotho",
                            NumericCode = (short)426
                        },
                        new
                        {
                            Alpha3Code = "lbr",
                            Alpha2Code = "lr",
                            EnglishName = "Liberia",
                            NumericCode = (short)430
                        },
                        new
                        {
                            Alpha3Code = "lby",
                            Alpha2Code = "ly",
                            EnglishName = "Libya",
                            NumericCode = (short)434
                        },
                        new
                        {
                            Alpha3Code = "lie",
                            Alpha2Code = "li",
                            EnglishName = "Liechtenstein",
                            NumericCode = (short)438
                        },
                        new
                        {
                            Alpha3Code = "ltu",
                            Alpha2Code = "lt",
                            EnglishName = "Lithuania",
                            NumericCode = (short)440
                        },
                        new
                        {
                            Alpha3Code = "lux",
                            Alpha2Code = "lu",
                            EnglishName = "Luxembourg",
                            NumericCode = (short)442
                        },
                        new
                        {
                            Alpha3Code = "mdg",
                            Alpha2Code = "mg",
                            EnglishName = "Madagascar",
                            NumericCode = (short)450
                        },
                        new
                        {
                            Alpha3Code = "mwi",
                            Alpha2Code = "mw",
                            EnglishName = "Malawi",
                            NumericCode = (short)454
                        },
                        new
                        {
                            Alpha3Code = "mys",
                            Alpha2Code = "my",
                            EnglishName = "Malaysia",
                            NumericCode = (short)458
                        },
                        new
                        {
                            Alpha3Code = "mdv",
                            Alpha2Code = "mv",
                            EnglishName = "Maldives",
                            NumericCode = (short)462
                        },
                        new
                        {
                            Alpha3Code = "mli",
                            Alpha2Code = "ml",
                            EnglishName = "Mali",
                            NumericCode = (short)466
                        },
                        new
                        {
                            Alpha3Code = "mlt",
                            Alpha2Code = "mt",
                            EnglishName = "Malta",
                            NumericCode = (short)470
                        },
                        new
                        {
                            Alpha3Code = "mhl",
                            Alpha2Code = "mh",
                            EnglishName = "Marshall Islands",
                            NumericCode = (short)584
                        },
                        new
                        {
                            Alpha3Code = "mrt",
                            Alpha2Code = "mr",
                            EnglishName = "Mauritania",
                            NumericCode = (short)478
                        },
                        new
                        {
                            Alpha3Code = "mus",
                            Alpha2Code = "mu",
                            EnglishName = "Mauritius",
                            NumericCode = (short)480
                        },
                        new
                        {
                            Alpha3Code = "mex",
                            Alpha2Code = "mx",
                            EnglishName = "Mexico",
                            NumericCode = (short)484
                        },
                        new
                        {
                            Alpha3Code = "fsm",
                            Alpha2Code = "fm",
                            EnglishName = "Micronesia, Federated States of",
                            NumericCode = (short)583
                        },
                        new
                        {
                            Alpha3Code = "mda",
                            Alpha2Code = "md",
                            EnglishName = "Moldova, Republic of",
                            NumericCode = (short)498
                        },
                        new
                        {
                            Alpha3Code = "mco",
                            Alpha2Code = "mc",
                            EnglishName = "Monaco",
                            NumericCode = (short)492
                        },
                        new
                        {
                            Alpha3Code = "mng",
                            Alpha2Code = "mn",
                            EnglishName = "Mongolia",
                            NumericCode = (short)496
                        },
                        new
                        {
                            Alpha3Code = "mne",
                            Alpha2Code = "me",
                            EnglishName = "Montenegro",
                            NumericCode = (short)499
                        },
                        new
                        {
                            Alpha3Code = "mar",
                            Alpha2Code = "ma",
                            EnglishName = "Morocco",
                            NumericCode = (short)504
                        },
                        new
                        {
                            Alpha3Code = "moz",
                            Alpha2Code = "mz",
                            EnglishName = "Mozambique",
                            NumericCode = (short)508
                        },
                        new
                        {
                            Alpha3Code = "mmr",
                            Alpha2Code = "mm",
                            EnglishName = "Myanmar",
                            NumericCode = (short)104
                        },
                        new
                        {
                            Alpha3Code = "nam",
                            Alpha2Code = "na",
                            EnglishName = "Namibia",
                            NumericCode = (short)516
                        },
                        new
                        {
                            Alpha3Code = "nru",
                            Alpha2Code = "nr",
                            EnglishName = "Nauru",
                            NumericCode = (short)520
                        },
                        new
                        {
                            Alpha3Code = "npl",
                            Alpha2Code = "np",
                            EnglishName = "Nepal",
                            NumericCode = (short)524
                        },
                        new
                        {
                            Alpha3Code = "nld",
                            Alpha2Code = "nl",
                            EnglishName = "Netherlands",
                            NumericCode = (short)528
                        },
                        new
                        {
                            Alpha3Code = "nzl",
                            Alpha2Code = "nz",
                            EnglishName = "New Zealand",
                            NumericCode = (short)554
                        },
                        new
                        {
                            Alpha3Code = "nic",
                            Alpha2Code = "ni",
                            EnglishName = "Nicaragua",
                            NumericCode = (short)558
                        },
                        new
                        {
                            Alpha3Code = "ner",
                            Alpha2Code = "ne",
                            EnglishName = "Niger",
                            NumericCode = (short)562
                        },
                        new
                        {
                            Alpha3Code = "nga",
                            Alpha2Code = "ng",
                            EnglishName = "Nigeria",
                            NumericCode = (short)566
                        },
                        new
                        {
                            Alpha3Code = "mkd",
                            Alpha2Code = "mk",
                            EnglishName = "North Macedonia",
                            NumericCode = (short)807
                        },
                        new
                        {
                            Alpha3Code = "nor",
                            Alpha2Code = "no",
                            EnglishName = "Norway",
                            NumericCode = (short)578
                        },
                        new
                        {
                            Alpha3Code = "omn",
                            Alpha2Code = "om",
                            EnglishName = "Oman",
                            NumericCode = (short)512
                        },
                        new
                        {
                            Alpha3Code = "pak",
                            Alpha2Code = "pk",
                            EnglishName = "Pakistan",
                            NumericCode = (short)586
                        },
                        new
                        {
                            Alpha3Code = "plw",
                            Alpha2Code = "pw",
                            EnglishName = "Palau",
                            NumericCode = (short)585
                        },
                        new
                        {
                            Alpha3Code = "pan",
                            Alpha2Code = "pa",
                            EnglishName = "Panama",
                            NumericCode = (short)591
                        },
                        new
                        {
                            Alpha3Code = "png",
                            Alpha2Code = "pg",
                            EnglishName = "Papua New Guinea",
                            NumericCode = (short)598
                        },
                        new
                        {
                            Alpha3Code = "pry",
                            Alpha2Code = "py",
                            EnglishName = "Paraguay",
                            NumericCode = (short)600
                        },
                        new
                        {
                            Alpha3Code = "per",
                            Alpha2Code = "pe",
                            EnglishName = "Peru",
                            NumericCode = (short)604
                        },
                        new
                        {
                            Alpha3Code = "phl",
                            Alpha2Code = "ph",
                            EnglishName = "Philippines",
                            NumericCode = (short)608
                        },
                        new
                        {
                            Alpha3Code = "pol",
                            Alpha2Code = "pl",
                            EnglishName = "Poland",
                            NumericCode = (short)616
                        },
                        new
                        {
                            Alpha3Code = "prt",
                            Alpha2Code = "pt",
                            EnglishName = "Portugal",
                            NumericCode = (short)620
                        },
                        new
                        {
                            Alpha3Code = "qat",
                            Alpha2Code = "qa",
                            EnglishName = "Qatar",
                            NumericCode = (short)634
                        },
                        new
                        {
                            Alpha3Code = "rou",
                            Alpha2Code = "ro",
                            EnglishName = "Romania",
                            NumericCode = (short)642
                        },
                        new
                        {
                            Alpha3Code = "rus",
                            Alpha2Code = "ru",
                            EnglishName = "Russian Federation",
                            NumericCode = (short)643
                        },
                        new
                        {
                            Alpha3Code = "rwa",
                            Alpha2Code = "rw",
                            EnglishName = "Rwanda",
                            NumericCode = (short)646
                        },
                        new
                        {
                            Alpha3Code = "kna",
                            Alpha2Code = "kn",
                            EnglishName = "Saint Kitts and Nevis",
                            NumericCode = (short)659
                        },
                        new
                        {
                            Alpha3Code = "lca",
                            Alpha2Code = "lc",
                            EnglishName = "Saint Lucia",
                            NumericCode = (short)662
                        },
                        new
                        {
                            Alpha3Code = "vct",
                            Alpha2Code = "vc",
                            EnglishName = "Saint Vincent and the Grenadines",
                            NumericCode = (short)670
                        },
                        new
                        {
                            Alpha3Code = "wsm",
                            Alpha2Code = "ws",
                            EnglishName = "Samoa",
                            NumericCode = (short)882
                        },
                        new
                        {
                            Alpha3Code = "smr",
                            Alpha2Code = "sm",
                            EnglishName = "San Marino",
                            NumericCode = (short)674
                        },
                        new
                        {
                            Alpha3Code = "stp",
                            Alpha2Code = "st",
                            EnglishName = "Sao Tome and Principe",
                            NumericCode = (short)678
                        },
                        new
                        {
                            Alpha3Code = "sau",
                            Alpha2Code = "sa",
                            EnglishName = "Saudi Arabia",
                            NumericCode = (short)682
                        },
                        new
                        {
                            Alpha3Code = "sen",
                            Alpha2Code = "sn",
                            EnglishName = "Senegal",
                            NumericCode = (short)686
                        },
                        new
                        {
                            Alpha3Code = "srb",
                            Alpha2Code = "rs",
                            EnglishName = "Serbia",
                            NumericCode = (short)688
                        },
                        new
                        {
                            Alpha3Code = "syc",
                            Alpha2Code = "sc",
                            EnglishName = "Seychelles",
                            NumericCode = (short)690
                        },
                        new
                        {
                            Alpha3Code = "sle",
                            Alpha2Code = "sl",
                            EnglishName = "Sierra Leone",
                            NumericCode = (short)694
                        },
                        new
                        {
                            Alpha3Code = "sgp",
                            Alpha2Code = "sg",
                            EnglishName = "Singapore",
                            NumericCode = (short)702
                        },
                        new
                        {
                            Alpha3Code = "svk",
                            Alpha2Code = "sk",
                            EnglishName = "Slovakia",
                            NumericCode = (short)703
                        },
                        new
                        {
                            Alpha3Code = "svn",
                            Alpha2Code = "si",
                            EnglishName = "Slovenia",
                            NumericCode = (short)705
                        },
                        new
                        {
                            Alpha3Code = "slb",
                            Alpha2Code = "sb",
                            EnglishName = "Solomon Islands",
                            NumericCode = (short)90
                        },
                        new
                        {
                            Alpha3Code = "som",
                            Alpha2Code = "so",
                            EnglishName = "Somalia",
                            NumericCode = (short)706
                        },
                        new
                        {
                            Alpha3Code = "zaf",
                            Alpha2Code = "za",
                            EnglishName = "South Africa",
                            NumericCode = (short)710
                        },
                        new
                        {
                            Alpha3Code = "ssd",
                            Alpha2Code = "ss",
                            EnglishName = "South Sudan",
                            NumericCode = (short)728
                        },
                        new
                        {
                            Alpha3Code = "esp",
                            Alpha2Code = "es",
                            EnglishName = "Spain",
                            NumericCode = (short)724
                        },
                        new
                        {
                            Alpha3Code = "lka",
                            Alpha2Code = "lk",
                            EnglishName = "Sri Lanka",
                            NumericCode = (short)144
                        },
                        new
                        {
                            Alpha3Code = "sdn",
                            Alpha2Code = "sd",
                            EnglishName = "Sudan",
                            NumericCode = (short)729
                        },
                        new
                        {
                            Alpha3Code = "sur",
                            Alpha2Code = "sr",
                            EnglishName = "Suriname",
                            NumericCode = (short)740
                        },
                        new
                        {
                            Alpha3Code = "swe",
                            Alpha2Code = "se",
                            EnglishName = "Sweden",
                            NumericCode = (short)752
                        },
                        new
                        {
                            Alpha3Code = "che",
                            Alpha2Code = "ch",
                            EnglishName = "Switzerland",
                            NumericCode = (short)756
                        },
                        new
                        {
                            Alpha3Code = "syr",
                            Alpha2Code = "sy",
                            EnglishName = "Syrian Arab Republic",
                            NumericCode = (short)760
                        },
                        new
                        {
                            Alpha3Code = "tjk",
                            Alpha2Code = "tj",
                            EnglishName = "Tajikistan",
                            NumericCode = (short)762
                        },
                        new
                        {
                            Alpha3Code = "tza",
                            Alpha2Code = "tz",
                            EnglishName = "Tanzania, United Republic of",
                            NumericCode = (short)834
                        },
                        new
                        {
                            Alpha3Code = "tha",
                            Alpha2Code = "th",
                            EnglishName = "Thailand",
                            NumericCode = (short)764
                        },
                        new
                        {
                            Alpha3Code = "tls",
                            Alpha2Code = "tl",
                            EnglishName = "Timor-Leste",
                            NumericCode = (short)626
                        },
                        new
                        {
                            Alpha3Code = "tgo",
                            Alpha2Code = "tg",
                            EnglishName = "Togo",
                            NumericCode = (short)768
                        },
                        new
                        {
                            Alpha3Code = "ton",
                            Alpha2Code = "to",
                            EnglishName = "Tonga",
                            NumericCode = (short)776
                        },
                        new
                        {
                            Alpha3Code = "tto",
                            Alpha2Code = "tt",
                            EnglishName = "Trinidad and Tobago",
                            NumericCode = (short)780
                        },
                        new
                        {
                            Alpha3Code = "tun",
                            Alpha2Code = "tn",
                            EnglishName = "Tunisia",
                            NumericCode = (short)788
                        },
                        new
                        {
                            Alpha3Code = "tur",
                            Alpha2Code = "tr",
                            EnglishName = "Türkiye",
                            NumericCode = (short)792
                        },
                        new
                        {
                            Alpha3Code = "tkm",
                            Alpha2Code = "tm",
                            EnglishName = "Turkmenistan",
                            NumericCode = (short)795
                        },
                        new
                        {
                            Alpha3Code = "tuv",
                            Alpha2Code = "tv",
                            EnglishName = "Tuvalu",
                            NumericCode = (short)798
                        },
                        new
                        {
                            Alpha3Code = "uga",
                            Alpha2Code = "ug",
                            EnglishName = "Uganda",
                            NumericCode = (short)800
                        },
                        new
                        {
                            Alpha3Code = "ukr",
                            Alpha2Code = "ua",
                            EnglishName = "Ukraine",
                            NumericCode = (short)804
                        },
                        new
                        {
                            Alpha3Code = "are",
                            Alpha2Code = "ae",
                            EnglishName = "United Arab Emirates",
                            NumericCode = (short)784
                        },
                        new
                        {
                            Alpha3Code = "gbr",
                            Alpha2Code = "gb",
                            EnglishName = "United Kingdom of Great Britain and Northern Ireland",
                            NumericCode = (short)826
                        },
                        new
                        {
                            Alpha3Code = "usa",
                            Alpha2Code = "us",
                            EnglishName = "United States of America",
                            NumericCode = (short)840
                        },
                        new
                        {
                            Alpha3Code = "ury",
                            Alpha2Code = "uy",
                            EnglishName = "Uruguay",
                            NumericCode = (short)858
                        },
                        new
                        {
                            Alpha3Code = "uzb",
                            Alpha2Code = "uz",
                            EnglishName = "Uzbekistan",
                            NumericCode = (short)860
                        },
                        new
                        {
                            Alpha3Code = "vut",
                            Alpha2Code = "vu",
                            EnglishName = "Vanuatu",
                            NumericCode = (short)548
                        },
                        new
                        {
                            Alpha3Code = "ven",
                            Alpha2Code = "ve",
                            EnglishName = "Venezuela, Bolivarian Republic of",
                            NumericCode = (short)862
                        },
                        new
                        {
                            Alpha3Code = "vnm",
                            Alpha2Code = "vn",
                            EnglishName = "Viet Nam",
                            NumericCode = (short)704
                        },
                        new
                        {
                            Alpha3Code = "yem",
                            Alpha2Code = "ye",
                            EnglishName = "Yemen",
                            NumericCode = (short)887
                        },
                        new
                        {
                            Alpha3Code = "zmb",
                            Alpha2Code = "zm",
                            EnglishName = "Zambia",
                            NumericCode = (short)894
                        },
                        new
                        {
                            Alpha3Code = "zwe",
                            Alpha2Code = "zw",
                            EnglishName = "Zimbabwe",
                            NumericCode = (short)716
                        });
                });

            modelBuilder.Entity("BankDataDb.Entities.Currency", b =>
                {
                    b.Property<string>("CurrencyCode")
                        .HasColumnType("char(3)")
                        .HasAnnotation("Relational:JsonPropertyName", "code");

                    b.Property<int>("MinorUnitFractions")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "decimal_digits");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("CurrencyCode");

                    b.HasIndex("CurrencyCode")
                        .IsUnique();

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            CurrencyCode = "USD",
                            MinorUnitFractions = 2,
                            Name = "US Dollar"
                        },
                        new
                        {
                            CurrencyCode = "CAD",
                            MinorUnitFractions = 2,
                            Name = "Canadian Dollar"
                        },
                        new
                        {
                            CurrencyCode = "EUR",
                            MinorUnitFractions = 2,
                            Name = "Euro"
                        },
                        new
                        {
                            CurrencyCode = "AED",
                            MinorUnitFractions = 2,
                            Name = "United Arab Emirates Dirham"
                        },
                        new
                        {
                            CurrencyCode = "AFN",
                            MinorUnitFractions = 0,
                            Name = "Afghan Afghani"
                        },
                        new
                        {
                            CurrencyCode = "ALL",
                            MinorUnitFractions = 0,
                            Name = "Albanian Lek"
                        },
                        new
                        {
                            CurrencyCode = "AMD",
                            MinorUnitFractions = 0,
                            Name = "Armenian Dram"
                        },
                        new
                        {
                            CurrencyCode = "ARS",
                            MinorUnitFractions = 2,
                            Name = "Argentine Peso"
                        },
                        new
                        {
                            CurrencyCode = "AUD",
                            MinorUnitFractions = 2,
                            Name = "Australian Dollar"
                        },
                        new
                        {
                            CurrencyCode = "AZN",
                            MinorUnitFractions = 2,
                            Name = "Azerbaijani Manat"
                        },
                        new
                        {
                            CurrencyCode = "BAM",
                            MinorUnitFractions = 2,
                            Name = "Bosnia-Herzegovina Convertible Mark"
                        },
                        new
                        {
                            CurrencyCode = "BDT",
                            MinorUnitFractions = 2,
                            Name = "Bangladeshi Taka"
                        },
                        new
                        {
                            CurrencyCode = "BGN",
                            MinorUnitFractions = 2,
                            Name = "Bulgarian Lev"
                        },
                        new
                        {
                            CurrencyCode = "BHD",
                            MinorUnitFractions = 3,
                            Name = "Bahraini Dinar"
                        },
                        new
                        {
                            CurrencyCode = "BIF",
                            MinorUnitFractions = 0,
                            Name = "Burundian Franc"
                        },
                        new
                        {
                            CurrencyCode = "BND",
                            MinorUnitFractions = 2,
                            Name = "Brunei Dollar"
                        },
                        new
                        {
                            CurrencyCode = "BOB",
                            MinorUnitFractions = 2,
                            Name = "Bolivian Boliviano"
                        },
                        new
                        {
                            CurrencyCode = "BRL",
                            MinorUnitFractions = 2,
                            Name = "Brazilian Real"
                        },
                        new
                        {
                            CurrencyCode = "BWP",
                            MinorUnitFractions = 2,
                            Name = "Botswanan Pula"
                        },
                        new
                        {
                            CurrencyCode = "BYN",
                            MinorUnitFractions = 2,
                            Name = "Belarusian Ruble"
                        },
                        new
                        {
                            CurrencyCode = "BZD",
                            MinorUnitFractions = 2,
                            Name = "Belize Dollar"
                        },
                        new
                        {
                            CurrencyCode = "CDF",
                            MinorUnitFractions = 2,
                            Name = "Congolese Franc"
                        },
                        new
                        {
                            CurrencyCode = "CHF",
                            MinorUnitFractions = 2,
                            Name = "Swiss Franc"
                        },
                        new
                        {
                            CurrencyCode = "CLP",
                            MinorUnitFractions = 0,
                            Name = "Chilean Peso"
                        },
                        new
                        {
                            CurrencyCode = "CNY",
                            MinorUnitFractions = 2,
                            Name = "Chinese Yuan"
                        },
                        new
                        {
                            CurrencyCode = "COP",
                            MinorUnitFractions = 0,
                            Name = "Colombian Peso"
                        },
                        new
                        {
                            CurrencyCode = "CRC",
                            MinorUnitFractions = 0,
                            Name = "Costa Rican Colón"
                        },
                        new
                        {
                            CurrencyCode = "CVE",
                            MinorUnitFractions = 2,
                            Name = "Cape Verdean Escudo"
                        },
                        new
                        {
                            CurrencyCode = "CZK",
                            MinorUnitFractions = 2,
                            Name = "Czech Republic Koruna"
                        },
                        new
                        {
                            CurrencyCode = "DJF",
                            MinorUnitFractions = 0,
                            Name = "Djiboutian Franc"
                        },
                        new
                        {
                            CurrencyCode = "DKK",
                            MinorUnitFractions = 2,
                            Name = "Danish Krone"
                        },
                        new
                        {
                            CurrencyCode = "DOP",
                            MinorUnitFractions = 2,
                            Name = "Dominican Peso"
                        },
                        new
                        {
                            CurrencyCode = "DZD",
                            MinorUnitFractions = 2,
                            Name = "Algerian Dinar"
                        },
                        new
                        {
                            CurrencyCode = "EEK",
                            MinorUnitFractions = 2,
                            Name = "Estonian Kroon"
                        },
                        new
                        {
                            CurrencyCode = "EGP",
                            MinorUnitFractions = 2,
                            Name = "Egyptian Pound"
                        },
                        new
                        {
                            CurrencyCode = "ERN",
                            MinorUnitFractions = 2,
                            Name = "Eritrean Nakfa"
                        },
                        new
                        {
                            CurrencyCode = "ETB",
                            MinorUnitFractions = 2,
                            Name = "Ethiopian Birr"
                        },
                        new
                        {
                            CurrencyCode = "GBP",
                            MinorUnitFractions = 2,
                            Name = "British Pound Sterling"
                        },
                        new
                        {
                            CurrencyCode = "GEL",
                            MinorUnitFractions = 2,
                            Name = "Georgian Lari"
                        },
                        new
                        {
                            CurrencyCode = "GHS",
                            MinorUnitFractions = 2,
                            Name = "Ghanaian Cedi"
                        },
                        new
                        {
                            CurrencyCode = "GNF",
                            MinorUnitFractions = 0,
                            Name = "Guinean Franc"
                        },
                        new
                        {
                            CurrencyCode = "GTQ",
                            MinorUnitFractions = 2,
                            Name = "Guatemalan Quetzal"
                        },
                        new
                        {
                            CurrencyCode = "HKD",
                            MinorUnitFractions = 2,
                            Name = "Hong Kong Dollar"
                        },
                        new
                        {
                            CurrencyCode = "HNL",
                            MinorUnitFractions = 2,
                            Name = "Honduran Lempira"
                        },
                        new
                        {
                            CurrencyCode = "HRK",
                            MinorUnitFractions = 2,
                            Name = "Croatian Kuna"
                        },
                        new
                        {
                            CurrencyCode = "HUF",
                            MinorUnitFractions = 0,
                            Name = "Hungarian Forint"
                        },
                        new
                        {
                            CurrencyCode = "IDR",
                            MinorUnitFractions = 0,
                            Name = "Indonesian Rupiah"
                        },
                        new
                        {
                            CurrencyCode = "ILS",
                            MinorUnitFractions = 2,
                            Name = "Israeli New Sheqel"
                        },
                        new
                        {
                            CurrencyCode = "INR",
                            MinorUnitFractions = 2,
                            Name = "Indian Rupee"
                        },
                        new
                        {
                            CurrencyCode = "IQD",
                            MinorUnitFractions = 0,
                            Name = "Iraqi Dinar"
                        },
                        new
                        {
                            CurrencyCode = "IRR",
                            MinorUnitFractions = 0,
                            Name = "Iranian Rial"
                        },
                        new
                        {
                            CurrencyCode = "ISK",
                            MinorUnitFractions = 0,
                            Name = "Icelandic Króna"
                        },
                        new
                        {
                            CurrencyCode = "JMD",
                            MinorUnitFractions = 2,
                            Name = "Jamaican Dollar"
                        },
                        new
                        {
                            CurrencyCode = "JOD",
                            MinorUnitFractions = 3,
                            Name = "Jordanian Dinar"
                        },
                        new
                        {
                            CurrencyCode = "JPY",
                            MinorUnitFractions = 0,
                            Name = "Japanese Yen"
                        },
                        new
                        {
                            CurrencyCode = "KES",
                            MinorUnitFractions = 2,
                            Name = "Kenyan Shilling"
                        },
                        new
                        {
                            CurrencyCode = "KHR",
                            MinorUnitFractions = 2,
                            Name = "Cambodian Riel"
                        },
                        new
                        {
                            CurrencyCode = "KMF",
                            MinorUnitFractions = 0,
                            Name = "Comorian Franc"
                        },
                        new
                        {
                            CurrencyCode = "KRW",
                            MinorUnitFractions = 0,
                            Name = "South Korean Won"
                        },
                        new
                        {
                            CurrencyCode = "KWD",
                            MinorUnitFractions = 3,
                            Name = "Kuwaiti Dinar"
                        },
                        new
                        {
                            CurrencyCode = "KZT",
                            MinorUnitFractions = 2,
                            Name = "Kazakhstani Tenge"
                        },
                        new
                        {
                            CurrencyCode = "LBP",
                            MinorUnitFractions = 0,
                            Name = "Lebanese Pound"
                        },
                        new
                        {
                            CurrencyCode = "LKR",
                            MinorUnitFractions = 2,
                            Name = "Sri Lankan Rupee"
                        },
                        new
                        {
                            CurrencyCode = "LTL",
                            MinorUnitFractions = 2,
                            Name = "Lithuanian Litas"
                        },
                        new
                        {
                            CurrencyCode = "LVL",
                            MinorUnitFractions = 2,
                            Name = "Latvian Lats"
                        },
                        new
                        {
                            CurrencyCode = "LYD",
                            MinorUnitFractions = 3,
                            Name = "Libyan Dinar"
                        },
                        new
                        {
                            CurrencyCode = "MAD",
                            MinorUnitFractions = 2,
                            Name = "Moroccan Dirham"
                        },
                        new
                        {
                            CurrencyCode = "MDL",
                            MinorUnitFractions = 2,
                            Name = "Moldovan Leu"
                        },
                        new
                        {
                            CurrencyCode = "MGA",
                            MinorUnitFractions = 0,
                            Name = "Malagasy Ariary"
                        },
                        new
                        {
                            CurrencyCode = "MKD",
                            MinorUnitFractions = 2,
                            Name = "Macedonian Denar"
                        },
                        new
                        {
                            CurrencyCode = "MMK",
                            MinorUnitFractions = 0,
                            Name = "Myanma Kyat"
                        },
                        new
                        {
                            CurrencyCode = "MOP",
                            MinorUnitFractions = 2,
                            Name = "Macanese Pataca"
                        },
                        new
                        {
                            CurrencyCode = "MUR",
                            MinorUnitFractions = 0,
                            Name = "Mauritian Rupee"
                        },
                        new
                        {
                            CurrencyCode = "MXN",
                            MinorUnitFractions = 2,
                            Name = "Mexican Peso"
                        },
                        new
                        {
                            CurrencyCode = "MYR",
                            MinorUnitFractions = 2,
                            Name = "Malaysian Ringgit"
                        },
                        new
                        {
                            CurrencyCode = "MZN",
                            MinorUnitFractions = 2,
                            Name = "Mozambican Metical"
                        },
                        new
                        {
                            CurrencyCode = "NAD",
                            MinorUnitFractions = 2,
                            Name = "Namibian Dollar"
                        },
                        new
                        {
                            CurrencyCode = "NGN",
                            MinorUnitFractions = 2,
                            Name = "Nigerian Naira"
                        },
                        new
                        {
                            CurrencyCode = "NIO",
                            MinorUnitFractions = 2,
                            Name = "Nicaraguan Córdoba"
                        },
                        new
                        {
                            CurrencyCode = "NOK",
                            MinorUnitFractions = 2,
                            Name = "Norwegian Krone"
                        },
                        new
                        {
                            CurrencyCode = "NPR",
                            MinorUnitFractions = 2,
                            Name = "Nepalese Rupee"
                        },
                        new
                        {
                            CurrencyCode = "NZD",
                            MinorUnitFractions = 2,
                            Name = "New Zealand Dollar"
                        },
                        new
                        {
                            CurrencyCode = "OMR",
                            MinorUnitFractions = 3,
                            Name = "Omani Rial"
                        },
                        new
                        {
                            CurrencyCode = "PAB",
                            MinorUnitFractions = 2,
                            Name = "Panamanian Balboa"
                        },
                        new
                        {
                            CurrencyCode = "PEN",
                            MinorUnitFractions = 2,
                            Name = "Peruvian Nuevo Sol"
                        },
                        new
                        {
                            CurrencyCode = "PHP",
                            MinorUnitFractions = 2,
                            Name = "Philippine Peso"
                        },
                        new
                        {
                            CurrencyCode = "PKR",
                            MinorUnitFractions = 0,
                            Name = "Pakistani Rupee"
                        },
                        new
                        {
                            CurrencyCode = "PLN",
                            MinorUnitFractions = 2,
                            Name = "Polish Zloty"
                        },
                        new
                        {
                            CurrencyCode = "PYG",
                            MinorUnitFractions = 0,
                            Name = "Paraguayan Guarani"
                        },
                        new
                        {
                            CurrencyCode = "QAR",
                            MinorUnitFractions = 2,
                            Name = "Qatari Rial"
                        },
                        new
                        {
                            CurrencyCode = "RON",
                            MinorUnitFractions = 2,
                            Name = "Romanian Leu"
                        },
                        new
                        {
                            CurrencyCode = "RSD",
                            MinorUnitFractions = 0,
                            Name = "Serbian Dinar"
                        },
                        new
                        {
                            CurrencyCode = "RUB",
                            MinorUnitFractions = 2,
                            Name = "Russian Ruble"
                        },
                        new
                        {
                            CurrencyCode = "RWF",
                            MinorUnitFractions = 0,
                            Name = "Rwandan Franc"
                        },
                        new
                        {
                            CurrencyCode = "SAR",
                            MinorUnitFractions = 2,
                            Name = "Saudi Riyal"
                        },
                        new
                        {
                            CurrencyCode = "SDG",
                            MinorUnitFractions = 2,
                            Name = "Sudanese Pound"
                        },
                        new
                        {
                            CurrencyCode = "SEK",
                            MinorUnitFractions = 2,
                            Name = "Swedish Krona"
                        },
                        new
                        {
                            CurrencyCode = "SGD",
                            MinorUnitFractions = 2,
                            Name = "Singapore Dollar"
                        },
                        new
                        {
                            CurrencyCode = "SOS",
                            MinorUnitFractions = 0,
                            Name = "Somali Shilling"
                        },
                        new
                        {
                            CurrencyCode = "SYP",
                            MinorUnitFractions = 0,
                            Name = "Syrian Pound"
                        },
                        new
                        {
                            CurrencyCode = "THB",
                            MinorUnitFractions = 2,
                            Name = "Thai Baht"
                        },
                        new
                        {
                            CurrencyCode = "TND",
                            MinorUnitFractions = 3,
                            Name = "Tunisian Dinar"
                        },
                        new
                        {
                            CurrencyCode = "TOP",
                            MinorUnitFractions = 2,
                            Name = "Tongan Paʻanga"
                        },
                        new
                        {
                            CurrencyCode = "TRY",
                            MinorUnitFractions = 2,
                            Name = "Turkish Lira"
                        },
                        new
                        {
                            CurrencyCode = "TTD",
                            MinorUnitFractions = 2,
                            Name = "Trinidad and Tobago Dollar"
                        },
                        new
                        {
                            CurrencyCode = "TWD",
                            MinorUnitFractions = 2,
                            Name = "New Taiwan Dollar"
                        },
                        new
                        {
                            CurrencyCode = "TZS",
                            MinorUnitFractions = 0,
                            Name = "Tanzanian Shilling"
                        },
                        new
                        {
                            CurrencyCode = "UAH",
                            MinorUnitFractions = 2,
                            Name = "Ukrainian Hryvnia"
                        },
                        new
                        {
                            CurrencyCode = "UGX",
                            MinorUnitFractions = 0,
                            Name = "Ugandan Shilling"
                        },
                        new
                        {
                            CurrencyCode = "UYU",
                            MinorUnitFractions = 2,
                            Name = "Uruguayan Peso"
                        },
                        new
                        {
                            CurrencyCode = "UZS",
                            MinorUnitFractions = 0,
                            Name = "Uzbekistan Som"
                        },
                        new
                        {
                            CurrencyCode = "VEF",
                            MinorUnitFractions = 2,
                            Name = "Venezuelan Bolívar"
                        },
                        new
                        {
                            CurrencyCode = "VND",
                            MinorUnitFractions = 0,
                            Name = "Vietnamese Dong"
                        },
                        new
                        {
                            CurrencyCode = "XAF",
                            MinorUnitFractions = 0,
                            Name = "CFA Franc BEAC"
                        },
                        new
                        {
                            CurrencyCode = "XOF",
                            MinorUnitFractions = 0,
                            Name = "CFA Franc BCEAO"
                        },
                        new
                        {
                            CurrencyCode = "YER",
                            MinorUnitFractions = 0,
                            Name = "Yemeni Rial"
                        },
                        new
                        {
                            CurrencyCode = "ZAR",
                            MinorUnitFractions = 2,
                            Name = "South African Rand"
                        },
                        new
                        {
                            CurrencyCode = "ZMK",
                            MinorUnitFractions = 0,
                            Name = "Zambian Kwacha"
                        },
                        new
                        {
                            CurrencyCode = "ZWL",
                            MinorUnitFractions = 0,
                            Name = "Zimbabwean Dollar"
                        });
                });

            modelBuilder.Entity("BankDataDb.Entities.Card", b =>
                {
                    b.HasOne("BankDataDb.Entities.Bank", "IssuedBank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IssuedBank");
                });

            modelBuilder.Entity("BankDataDb.Entities.CardTransaction", b =>
                {
                    b.HasOne("BankDataDb.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryAlpha3Code");

                    b.HasOne("BankDataDb.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Currency");
                });
#pragma warning restore 612, 618
        }
    }
}
